<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lab Ten – Point Estimation – Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#lab-8-notes" id="toc-lab-8-notes" class="nav-link active" data-scroll-target="#lab-8-notes"><span class="header-section-number">1</span> Lab 8 Notes</a>
  <ul class="collapse">
  <li><a href="#althams-multiplicative-binomial-distribution" id="toc-althams-multiplicative-binomial-distribution" class="nav-link" data-scroll-target="#althams-multiplicative-binomial-distribution"><span class="header-section-number">1.1</span> Altham’s Multiplicative Binomial Distribution</a></li>
  </ul></li>
  <li><a href="#althams-multiplicative-beta-binomial-distribution" id="toc-althams-multiplicative-beta-binomial-distribution" class="nav-link" data-scroll-target="#althams-multiplicative-beta-binomial-distribution"><span class="header-section-number">2</span> Altham’s Multiplicative Beta Binomial Distribution</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1"><span class="header-section-number">3</span> Question 1</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a"><span class="header-section-number">3.1</span> Part a</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b"><span class="header-section-number">3.2</span> Part b</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c"><span class="header-section-number">3.3</span> Part c</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2"><span class="header-section-number">4</span> Question 2</a>
  <ul class="collapse">
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1"><span class="header-section-number">4.1</span> Part a</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1"><span class="header-section-number">4.2</span> Part b</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1"><span class="header-section-number">4.3</span> Part c</a></li>
  <li><a href="#part-d" id="toc-part-d" class="nav-link" data-scroll-target="#part-d"><span class="header-section-number">4.4</span> Part d</a></li>
  </ul></li>
  <li><a href="#lab-10" id="toc-lab-10" class="nav-link" data-scroll-target="#lab-10"><span class="header-section-number">5</span> Lab 10</a>
  <ul class="collapse">
  <li><a href="#summarize-the-2024-data" id="toc-summarize-the-2024-data" class="nav-link" data-scroll-target="#summarize-the-2024-data"><span class="header-section-number">5.1</span> Summarize the 2024 Data</a></li>
  <li><a href="#althams-multiplicative-binomial-distribution-1" id="toc-althams-multiplicative-binomial-distribution-1" class="nav-link" data-scroll-target="#althams-multiplicative-binomial-distribution-1"><span class="header-section-number">5.2</span> Altham’s Multiplicative Binomial Distribution</a></li>
  <li><a href="#althams-multiplicative-beta-binomial-distribution-1" id="toc-althams-multiplicative-beta-binomial-distribution-1" class="nav-link" data-scroll-target="#althams-multiplicative-beta-binomial-distribution-1"><span class="header-section-number">5.3</span> Altham’s Multiplicative Beta Binomial Distribution</a></li>
  <li><a href="#executive-summary" id="toc-executive-summary" class="nav-link" data-scroll-target="#executive-summary"><span class="header-section-number">5.4</span> Executive Summary</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab10WriteUp.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab Ten – Point Estimation</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p></p>
<p></p>
<p><strong>Tips</strong></p>
<ul>
<li>Complete the tasks below. Make sure to start your solutions in on a new line that starts with “<strong>Solution</strong>:”.</li>
<li>Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab <em>much</em> easier.</li>
<li>Make sure to use “enter” to make your code readable, so it doesn’t run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you’re submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.</li>
<li>Don’t forget that you can copy-and-paste code when you’re doing something similar as we did in class!</li>
<li>Make sure to plot all computed probabilities. This is good <code>ggplot</code> practice AND will help make sure you don’t make a mistake when computing the probability.</li>
</ul>
<section id="lab-8-notes" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Lab 8 Notes</h1>
<section id="althams-multiplicative-binomial-distribution" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="althams-multiplicative-binomial-distribution"><span class="header-section-number">1.1</span> Altham’s Multiplicative Binomial Distribution</h2>
<p>The PMF for Altham’s Multiplicative Binomial Distribution is <span class="math display">\[f_X(x) = \frac{1}{c} {n \choose x} p^x (1-p)^{n-x} \theta^{x(n-x)}I(x \in \{0, 1, ..., n\})\]</span> where <span class="math display">\[c = \sum_{i=0}^n {n \choose i} p^i (1-p)^{n-i} \theta^{i(n-i)}.\]</span> Just so we start on the same page, I have included my <code>R</code> function for computing probability using this distribution.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>daltbinom <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, prob, theta){</span>
<span id="cb1-2"><a href="#cb1-2"></a>  normalizing.constant <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>size){</span>
<span id="cb1-4"><a href="#cb1-4"></a>    normalizing.constant <span class="ot">&lt;-</span> normalizing.constant <span class="sc">+</span> </span>
<span id="cb1-5"><a href="#cb1-5"></a>      <span class="fu">choose</span>(size, j) <span class="sc">*</span> prob<span class="sc">^</span>j <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>prob)<span class="sc">^</span>(size<span class="sc">-</span>j) <span class="sc">*</span> theta<span class="sc">^</span>(j<span class="sc">*</span>(size<span class="sc">-</span>j))</span>
<span id="cb1-6"><a href="#cb1-6"></a>  }</span>
<span id="cb1-7"><a href="#cb1-7"></a>  <span class="co"># Probability Mass at x=x</span></span>
<span id="cb1-8"><a href="#cb1-8"></a>  (<span class="dv">1</span><span class="sc">/</span>normalizing.constant) <span class="sc">*</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>    <span class="fu">choose</span>(size, x) <span class="sc">*</span> prob<span class="sc">^</span>x <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>prob)<span class="sc">^</span>(size<span class="sc">-</span>x) <span class="sc">*</span> theta<span class="sc">^</span>(x<span class="sc">*</span>(size<span class="sc">-</span>x)) <span class="sc">*</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>      (x<span class="sc">&gt;=</span><span class="dv">0</span>)<span class="sc">*</span>(x<span class="sc">&lt;=</span>size)</span>
<span id="cb1-11"><a href="#cb1-11"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
</section>
<section id="althams-multiplicative-beta-binomial-distribution" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Altham’s Multiplicative Beta Binomial Distribution</h1>
<p>The PMF for Altham’s Multiplicative Beta Binomial Distribution is <span class="math display">\[f_X(x) = \left[\int_{0}^1 \left(\frac{1}{c} {n \choose x} p^x (1-p)^{n-x} \theta^{x(n-x)}\right)\left(\frac{\Gamma(\alpha+\beta)}{\Gamma(\alpha)\Gamma(\beta)} p^{\alpha-1}(1-p)^{\beta-1}\right) dp\right]I(x \in \{0, 1, ..., n\})\]</span></p>
<p>Just so we start on the same page, I have included my <code>R</code> function for computing probability using this distribution.</p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>daltbbinom.single <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, alpha, beta, theta){</span>
<span id="cb2-2"><a href="#cb2-2"></a>    integrand <span class="ot">&lt;-</span> <span class="cf">function</span>(p) {</span>
<span id="cb2-3"><a href="#cb2-3"></a>    <span class="fu">sapply</span>(p, <span class="co"># integrate will pass in a vector, so we use sapply to apply the following</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>           <span class="cf">function</span>(p_val){</span>
<span id="cb2-5"><a href="#cb2-5"></a>             <span class="co"># f(x|p) * f(p|alpha, beta)</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>             <span class="fu">daltbinom</span>(x, size, p_val, theta) <span class="sc">*</span> <span class="fu">dbeta</span>(p_val, alpha, beta)</span>
<span id="cb2-7"><a href="#cb2-7"></a>           }</span>
<span id="cb2-8"><a href="#cb2-8"></a>    )</span>
<span id="cb2-9"><a href="#cb2-9"></a>  }</span>
<span id="cb2-10"><a href="#cb2-10"></a>  <span class="co"># Probability Mass at x=x</span></span>
<span id="cb2-11"><a href="#cb2-11"></a>  <span class="co"># integrate(integrand, lower = 0, upper = 1)$value * (x&gt;=0)*(x&lt;=size)</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>  <span class="co"># I shrink the bounds below to avoid log(0)=-infinty</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>  <span class="co"># I use try() to catch when there is an error and avoid crashing</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>  res <span class="ot">&lt;-</span> <span class="fu">try</span>(<span class="fu">integrate</span>(integrand, <span class="at">lower =</span> <span class="fl">1e-7</span>, <span class="at">upper =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">1e-7</span>)<span class="sc">$</span>value <span class="sc">*</span> </span>
<span id="cb2-15"><a href="#cb2-15"></a>                  (x<span class="sc">&gt;=</span><span class="dv">0</span>)<span class="sc">*</span>(x<span class="sc">&lt;=</span>size), </span>
<span id="cb2-16"><a href="#cb2-16"></a>             <span class="at">silent =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-17"><a href="#cb2-17"></a>  <span class="co"># If there is an error, return a near-zero probability</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>  <span class="cf">if</span>(<span class="fu">inherits</span>(res, <span class="st">"try-error"</span>)) <span class="fu">return</span>(<span class="fl">0.1</span><span class="sc">^</span><span class="dv">6</span>)</span>
<span id="cb2-19"><a href="#cb2-19"></a>  </span>
<span id="cb2-20"><a href="#cb2-20"></a>  res</span>
<span id="cb2-21"><a href="#cb2-21"></a>}</span>
<span id="cb2-22"><a href="#cb2-22"></a><span class="co"># Write a function that works on a vector</span></span>
<span id="cb2-23"><a href="#cb2-23"></a>daltbbinom <span class="ot">&lt;-</span> <span class="cf">function</span>(x, size, alpha, beta, theta){</span>
<span id="cb2-24"><a href="#cb2-24"></a>  <span class="fu">sapply</span>(<span class="at">X=</span>x, <span class="at">FUN=</span>daltbbinom.single, <span class="at">size=</span>size, <span class="at">alpha=</span>alpha, <span class="at">beta=</span>beta, <span class="at">theta=</span>theta)</span>
<span id="cb2-25"><a href="#cb2-25"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="question-1" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Question 1</h1>
<p>In Lab 8, we use Altham’s Multiplicative Binomial Distribution. Your job was to interpret the impact of <span class="math inline">\(\theta\)</span> in that equation. In this lab, we will model the number of legs won in a best of eleven (first to six) match.</p>
<p>To help us think about the interpretation, something that was challenging before, let’s try something a little more manageable.</p>
<section id="part-a" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="part-a"><span class="header-section-number">3.1</span> Part a</h2>
<p>Suppose a player has a 50% chance of winning a specific leg, that is let <span class="math inline">\(p=0.50\)</span>. Let’s look at the probability they win (<span class="math inline">\(x=6\)</span>) legs in the match. Compute this probability over a sequence from <span class="math inline">\(\theta=0.5\)</span> to <span class="math inline">\(\theta=1.5\)</span> and plot it using a line where the <span class="math inline">\(x\)</span>-axis is <span class="math inline">\(\theta\)</span> and the <span class="math inline">\(y\)</span>-axis is <span class="math inline">\(P(X=6)\)</span>.</p>
<p><strong>Solution:</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co">#computing probabilities</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>p <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb3-3"><a href="#cb3-3"></a>thetas <span class="ot">=</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fl">0.5</span>,<span class="at">to=</span><span class="fl">1.5</span>,<span class="at">by=</span><span class="fl">0.01</span>)</span>
<span id="cb3-4"><a href="#cb3-4"></a>probabilities <span class="ot">=</span> <span class="fu">daltbinom</span>(<span class="at">x=</span><span class="dv">6</span>,<span class="at">size=</span><span class="dv">11</span>,<span class="at">prob=</span>p,<span class="at">theta=</span>thetas)</span>
<span id="cb3-5"><a href="#cb3-5"></a></span>
<span id="cb3-6"><a href="#cb3-6"></a><span class="co">#creating data for plots</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>ggdat <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb3-8"><a href="#cb3-8"></a>    <span class="at">theta =</span> thetas,</span>
<span id="cb3-9"><a href="#cb3-9"></a>    <span class="at">probs =</span> probabilities</span>
<span id="cb3-10"><a href="#cb3-10"></a>)</span>
<span id="cb3-11"><a href="#cb3-11"></a></span>
<span id="cb3-12"><a href="#cb3-12"></a><span class="co">#plot</span></span>
<span id="cb3-13"><a href="#cb3-13"></a>  ggdat <span class="sc">|&gt;</span> </span>
<span id="cb3-14"><a href="#cb3-14"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> theta, </span>
<span id="cb3-15"><a href="#cb3-15"></a>               <span class="at">y =</span> probs)) <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16"></a>    <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb3-17"><a href="#cb3-17"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb3-18"><a href="#cb3-18"></a>    <span class="fu">ylab</span>(<span class="st">"P(X=6)"</span>) <span class="sc">+</span></span>
<span id="cb3-19"><a href="#cb3-19"></a>    <span class="fu">xlab</span>(<span class="st">"Theta"</span>) <span class="sc">+</span></span>
<span id="cb3-20"><a href="#cb3-20"></a>    <span class="fu">ggtitle</span>(<span class="st">"P(X=6) for Theta from 0.5 to 1.5"</span>) <span class="sc">+</span></span>
<span id="cb3-21"><a href="#cb3-21"></a>    <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p></p>
</section>
<section id="part-b" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="part-b"><span class="header-section-number">3.2</span> Part b</h2>
<p>Now, plot Altham’s Multiplicative Binomial Distribution under the same parameters with <span class="math inline">\(\theta=0.50\)</span>, <span class="math inline">\(\theta=1\)</span>, and <span class="math inline">\(\theta=1.5\)</span>. Use <code>ncol=1</code> in <code>facet_wrap()</code> to plot the PMFs in a single column for comparing.</p>
<p><strong>Solution:</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co">#computing PMFs</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>p <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>x.vals <span class="ot">=</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>,<span class="at">to=</span><span class="dv">11</span>,<span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb4-4"><a href="#cb4-4"></a></span>
<span id="cb4-5"><a href="#cb4-5"></a><span class="co">#theta=0.5</span></span>
<span id="cb4-6"><a href="#cb4-6"></a>probabilities<span class="fl">.05</span> <span class="ot">=</span> <span class="fu">daltbinom</span>(<span class="at">x=</span>x.vals,<span class="at">size=</span><span class="dv">11</span>,<span class="at">prob=</span>p,<span class="at">theta=</span><span class="fl">0.5</span>)</span>
<span id="cb4-7"><a href="#cb4-7"></a></span>
<span id="cb4-8"><a href="#cb4-8"></a><span class="co">#theta=1</span></span>
<span id="cb4-9"><a href="#cb4-9"></a>probabilities<span class="fl">.1</span> <span class="ot">=</span> <span class="fu">daltbinom</span>(<span class="at">x=</span>x.vals,<span class="at">size=</span><span class="dv">11</span>,<span class="at">prob=</span>p,<span class="at">theta=</span><span class="dv">1</span>)</span>
<span id="cb4-10"><a href="#cb4-10"></a></span>
<span id="cb4-11"><a href="#cb4-11"></a><span class="co">#theta=1.5</span></span>
<span id="cb4-12"><a href="#cb4-12"></a>probabilities<span class="fl">.15</span> <span class="ot">=</span> <span class="fu">daltbinom</span>(<span class="at">x=</span>x.vals,<span class="at">size=</span><span class="dv">11</span>,<span class="at">prob=</span>p,<span class="at">theta=</span><span class="fl">1.5</span>)</span>
<span id="cb4-13"><a href="#cb4-13"></a></span>
<span id="cb4-14"><a href="#cb4-14"></a>ggdat <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb4-15"><a href="#cb4-15"></a>  <span class="at">theta =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Theta = 0.5"</span>,<span class="st">"Theta = 1"</span>,<span class="st">"Theta = 1.5"</span>),<span class="at">each=</span><span class="dv">12</span>),</span>
<span id="cb4-16"><a href="#cb4-16"></a>  <span class="at">x =</span> <span class="fu">rep</span>(x.vals,<span class="dv">3</span>),</span>
<span id="cb4-17"><a href="#cb4-17"></a>  <span class="at">prob =</span> <span class="fu">c</span>(probabilities<span class="fl">.05</span>,probabilities<span class="fl">.1</span>,probabilities<span class="fl">.15</span>)</span>
<span id="cb4-18"><a href="#cb4-18"></a>)</span>
<span id="cb4-19"><a href="#cb4-19"></a></span>
<span id="cb4-20"><a href="#cb4-20"></a>ggdat <span class="sc">|&gt;</span></span>
<span id="cb4-21"><a href="#cb4-21"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x,</span>
<span id="cb4-22"><a href="#cb4-22"></a>             <span class="at">y =</span> prob)) <span class="sc">+</span></span>
<span id="cb4-23"><a href="#cb4-23"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> theta,<span class="at">ncol=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-24"><a href="#cb4-24"></a>    <span class="fu">geom_linerange</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, </span>
<span id="cb4-25"><a href="#cb4-25"></a>                       <span class="at">ymin =</span> <span class="dv">0</span>, </span>
<span id="cb4-26"><a href="#cb4-26"></a>                       <span class="at">ymax =</span> prob)) <span class="sc">+</span></span>
<span id="cb4-27"><a href="#cb4-27"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb4-28"><a href="#cb4-28"></a>  <span class="fu">xlab</span>(<span class="st">"P(X=x)"</span>) <span class="sc">+</span></span>
<span id="cb4-29"><a href="#cb4-29"></a>  <span class="fu">ylab</span>(<span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30"></a>  <span class="fu">ggtitle</span>(<span class="st">"Altham's Multiplicative Binomial PMF for Theta = 0.5, 1, 1.5"</span>) <span class="sc">+</span></span>
<span id="cb4-31"><a href="#cb4-31"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p></p>
</section>
<section id="part-c" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="part-c"><span class="header-section-number">3.3</span> Part c</h2>
<p>What is your best assessment of what <span class="math inline">\(\theta\)</span> is doing in this setting. Consider when a 6-0 blowout is most likely, and when a 5-6 nail-biter is most likely. Note here we should treat the match as a fixed <span class="math inline">\(n=11\)</span> as we did for <span class="math inline">\(n=3\)</span> in Lab 8.<br>
<strong>Note:</strong> In lab 8, we saw that small <span class="math inline">\(\theta\)</span> meant wins came in bunches (clumped together), so there were more 2-0 wins in a best of three series.</p>
<p><strong>Solution:</strong> It appears as though the parameter <span class="math inline">\(\theta\)</span> directly affects the shape of the PMF. Low values of <span class="math inline">\(\theta\)</span> cluster outcomes/successes toward extreme scenarios (“sweeps”). Larger values for <span class="math inline">\(\theta\)</span> appear to do the opposite, clustering outcomes toward the center and reducing the likelihood of these sweeps occurring. Therefore, 6-0 blowouts are more likely for lower <span class="math inline">\(\theta\)</span>, while 5-6 nail-biters are more likely for larger <span class="math inline">\(\theta\)</span>. Based on this, I assume that <span class="math inline">\(\theta\)</span> must model momentum, with smaller <span class="math inline">\(\theta\)</span> increasing the effect of momentum on each subsequent round and vice versa.</p>
</section>
</section>
<section id="question-2" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Question 2</h1>
<section id="part-a-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="part-a-1"><span class="header-section-number">4.1</span> Part a</h2>
<p>Altham’s Multiplicative Binomial Distribution does not typically simplify to the clean <span class="math inline">\(E(X)=np\)</span> seen in the Binomial distribution, unless <span class="math inline">\(\theta = 1\)</span>. Write out the expression that would need to be solved to find <span class="math inline">\(E(X^k)\)</span>, and then write a function that computes it given the proposed parameter values <span class="math inline">\(p\)</span> (<code>prob</code>) and <span class="math inline">\(\theta\)</span> (<code>theta</code>).</p>
<p><strong>Solution:</strong> The expression that would need to be solved to find <span class="math inline">\(E(X^k)\)</span> is the following: <span class="math display">\[ E(X^k) = \sum_{x=-\infty}^{\infty} x^kf_{X}(x) \]</span></p>
<p>Note that it doesn’t matter if the sum’s lower limit is <span class="math inline">\(-\infty\)</span>, <span class="math inline">\(0\)</span>, or any value in between. This is because the PMF <span class="math inline">\(f_{X}(x)\)</span> includes an indicator function, <span class="math inline">\(I(x \in \{0, 1, ..., n\})\)</span>, that forces the PMF to equal <span class="math inline">\(0\)</span> for any <span class="math inline">\(x\)</span> outside of the specified support. When evaluating this computationally, we will exclusively sum over the support.</p>
<p><em>Function:</em></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>altbinom.moments <span class="ot">=</span> <span class="cf">function</span>(n,k,prob,theta){</span>
<span id="cb5-2"><a href="#cb5-2"></a>  x.vals <span class="ot">=</span> <span class="dv">0</span><span class="sc">:</span>n</span>
<span id="cb5-3"><a href="#cb5-3"></a>  pmf.vals <span class="ot">=</span> <span class="fu">daltbinom</span>(<span class="at">x=</span>x.vals,<span class="at">size=</span>n,<span class="at">prob=</span>prob,<span class="at">theta=</span>theta)</span>
<span id="cb5-4"><a href="#cb5-4"></a>  <span class="fu">sum</span>(x.vals<span class="sc">^</span>k <span class="sc">*</span> pmf.vals)</span>
<span id="cb5-5"><a href="#cb5-5"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="part-b-1" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="part-b-1"><span class="header-section-number">4.2</span> Part b</h2>
<p>Describe how you can use your answer to part a to find Method of Moments estimates for the parameters <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for Altham’s Multiplicative Binomial Distribution based on data.</p>
<p><strong>Solution:</strong><br>
To find parameters using our data and our Method of Moments function, we can build a function that takes in a vector of parameters and the data. The first thing this function will do is extract the parameters (<span class="math inline">\(p\)</span> = <code>par[1]</code> and <span class="math inline">\(\theta\)</span> = <code>par[2]</code>) using vector indexing. Then, it will calculate the first two sample moments <code>m1</code> <span class="math inline">\(= \overline{x}\)</span> and <code>m2</code> <span class="math inline">\(= \overline{x^2}\)</span> (<code>mean(x)</code>, <code>mean(x^2)</code>. Note that only the first two moments are needed for Altham’s Multiplicative Binomial Distribution because there are only two unknown parameters. After this, we write expressions for the theoretical population moments <code>E1</code> <span class="math inline">\(= E(X)\)</span> and <code>E2</code> = <span class="math inline">\(E(X^2)\)</span> as functions of the parameters. Then, we end the function by returning a vector for which the entries are <code>E1-m1</code> and <code>E2-m2</code>.</p>
<p>After creating this function, we obtain our Method of Moments estimates using <code>nleqslv::nleqslv</code> with an initial guess for our parameters, the function we just defined, and the data. The solver will then do all the computational work for us and produce parameters that make both <code>E1-m1</code> and <code>E2-m2</code> as close to 0 as possible.</p>
</section>
<section id="part-c-1" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="part-c-1"><span class="header-section-number">4.3</span> Part c</h2>
<p>Write a function that computes the log-likelihood for Altham’s Multiplicative Binomial Distribution, given data (<code>x</code>) and proposed parameter values <span class="math inline">\(p\)</span> (<code>prob</code>) and <span class="math inline">\(\theta\)</span> (<code>theta</code>). Note that parameter values are inputted as a vector (<span class="math inline">\(p\)</span> = <code>par[1]</code>, <span class="math inline">\(\theta\)</span> = <code>par[2]</code>) to agree with the input structure of <code>optim()</code>, which we will later use to obtain our maximum likelihood estimates.</p>
<p>We also include an <code>ifelse()</code> statement that returns the negative log-likelihood function when <code>mle</code> is true. The reasoning for this is explained in part d.</p>
<p><strong>Solution:</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>llaltbinom <span class="ot">=</span> <span class="cf">function</span>(par, x, n, <span class="at">mle=</span>F){</span>
<span id="cb6-2"><a href="#cb6-2"></a>  p <span class="ot">=</span> <span class="fu">ifelse</span>(mle, <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(<span class="sc">-</span>par[<span class="dv">1</span>])), par[<span class="dv">1</span>]) </span>
<span id="cb6-3"><a href="#cb6-3"></a>  theta <span class="ot">=</span>  <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">2</span>]), par[<span class="dv">2</span>])</span>
<span id="cb6-4"><a href="#cb6-4"></a>  ll <span class="ot">=</span> <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">daltbinom</span>(<span class="at">x =</span> x, <span class="at">size =</span> n, <span class="at">prob =</span> p, <span class="at">theta =</span> theta)))</span>
<span id="cb6-5"><a href="#cb6-5"></a>  <span class="fu">ifelse</span>(mle, <span class="sc">-</span>ll,ll)</span>
<span id="cb6-6"><a href="#cb6-6"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p></p>
</section>
<section id="part-d" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="part-d"><span class="header-section-number">4.4</span> Part d</h2>
<p>Describe how you can use your answer to part c to find Maximum Likelihood estimates for the parameters <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for Altham’s Multiplicative Binomial Distribution based on data.</p>
<p><strong>Solution:</strong><br>
We can use the <code>optim()</code> function, which finds a function’s minimum. To do this, we call <code>optim()</code> with the arguments <code>par</code> (vector containing initial guesses for parameters <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>), <code>fn</code> (= llaltbinom), <code>x</code> (the column of data we are interested in), and specify <code>mle = T</code>. This last step is crucial; if we want to use <code>optim()</code> to find a maximum, we minimize the negative log-likelihood, which is the equivalent to maximizing the log-likelihood.</p>
</section>
</section>
<section id="lab-10" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Lab 10</h1>
<p>Peter “Snakebite” Wright is a two-time Professional Darts Corporation World Champion (2020, 2022) and a former World No.&nbsp;1. He is one of the sport’s most decorated players, winning nearly 50 PDC titles including the World Matchplay, UK Open, and multiple European Championships.</p>
<p>In 2024, he made The Premier League – a league involving the eight best players that runs every Thursday night from February to May. In this season, he won two of eighteen matches, securing only four points. The spread in legs won was -43, meaning he lost 43 more legs than he won. This performance was rather quite bad. He was soundly trounced in almost all his match ups.</p>
<p>The 2024 standings are below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Rank</th>
<th style="text-align: left;">Player</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Luke Littler</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Luke Humphries</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Michael van Gerwen</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Michael Smith</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Nathan Aspinall</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Rob Cross</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Gerwyn Price</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">Peter Wright</td>
</tr>
</tbody>
</table>
<section id="summarize-the-2024-data" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="summarize-the-2024-data"><span class="header-section-number">5.1</span> Summarize the 2024 Data</h2>
<p>In <code>pdc2024.csv</code>, I have provided the data for the 2024 Premier League season. There are a few data cleaning steps to consider.</p>
<ul>
<li>Remove any matches with no <code>Score</code> (e.g., a bye or walkover)</li>
<li>Nights 1 through 16 are best of 11 (first to 6), but the playoffs are extended. For consistency, keep nights 1 through 16 only.</li>
<li>Make two columns <code>WinnerLegs</code> and <code>LoserLegs</code> that keep track of the number of legs each player has won</li>
</ul>
<p>Summarize the data. What do the data tell us about the breakdown of the results?</p>
<p><strong>Solution:</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co">#Cleaning</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>pdc.dat <span class="ot">=</span> <span class="fu">read_csv</span>(<span class="st">"pdc2024.csv"</span>)</span>
<span id="cb7-3"><a href="#cb7-3"></a>pdc.dat <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">filter</span>(Night <span class="sc">%in%</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span> <span class="sc">&amp;</span> Score <span class="sc">!=</span> <span class="st">"w/o"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="fu">separate</span>(Score, <span class="at">into=</span><span class="fu">c</span>(<span class="st">"WinnerLegs"</span>, <span class="st">"LoserLegs"</span>),<span class="at">sep=</span><span class="st">"-"</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-6"><a href="#cb7-6"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-7"><a href="#cb7-7"></a>    <span class="at">WinnerLegs =</span> <span class="fu">as.numeric</span>(WinnerLegs),</span>
<span id="cb7-8"><a href="#cb7-8"></a>    <span class="at">LoserLegs  =</span> <span class="fu">as.numeric</span>(LoserLegs)</span>
<span id="cb7-9"><a href="#cb7-9"></a>  )</span>
<span id="cb7-10"><a href="#cb7-10"></a></span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="co">#Summary</span></span>
<span id="cb7-12"><a href="#cb7-12"></a>pdc.dat <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb7-13"><a href="#cb7-13"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-14"><a href="#cb7-14"></a>    <span class="at">LegDifference =</span> WinnerLegs <span class="sc">-</span> LoserLegs</span>
<span id="cb7-15"><a href="#cb7-15"></a>  )</span>
<span id="cb7-16"><a href="#cb7-16"></a></span>
<span id="cb7-17"><a href="#cb7-17"></a>(<span class="at">pdc.sum =</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb7-18"><a href="#cb7-18"></a>  <span class="fu">summarize</span>(</span>
<span id="cb7-19"><a href="#cb7-19"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(LegDifference),</span>
<span id="cb7-20"><a href="#cb7-20"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(LegDifference),</span>
<span id="cb7-21"><a href="#cb7-21"></a>    <span class="at">median =</span> <span class="fu">median</span>(LegDifference),</span>
<span id="cb7-22"><a href="#cb7-22"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(LegDifference),</span>
<span id="cb7-23"><a href="#cb7-23"></a>    <span class="at">min =</span> <span class="fu">min</span>(LegDifference),</span>
<span id="cb7-24"><a href="#cb7-24"></a>    <span class="at">max =</span> <span class="fu">max</span>(LegDifference),</span>
<span id="cb7-25"><a href="#cb7-25"></a>    <span class="at">skew =</span> e1071<span class="sc">::</span><span class="fu">skewness</span>(LegDifference),</span>
<span id="cb7-26"><a href="#cb7-26"></a>    <span class="at">ekurt =</span> e1071<span class="sc">::</span><span class="fu">kurtosis</span>(LegDifference)</span>
<span id="cb7-27"><a href="#cb7-27"></a>  ))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
   mean    sd median   IQR   min   max  skew  ekurt
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1  2.44  1.20      2     2     1     5 0.374 -0.846</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co">#Visualization</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">ggplot</span>(pdc.dat) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(LegDifference),</span>
<span id="cb9-4"><a href="#cb9-4"></a>               <span class="at">y =</span> <span class="fu">after_stat</span>(count<span class="sc">/</span><span class="fu">sum</span>(count)))) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-7"><a href="#cb9-7"></a>    <span class="at">x =</span> <span class="st">"Leg Difference"</span>,</span>
<span id="cb9-8"><a href="#cb9-8"></a>    <span class="at">y =</span> <span class="st">"Proportion of Matches"</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab10WriteUp_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p></p>
<p><em>Interpretation of Results:</em> The numerical summary tells us that the median leg difference in each match is 2 and that the middle 50% of matches (IQR) are between 1-leg wins and 3-leg wins. We analyze median and IQR in place of mean and standard deviation due to the data’s right skewness (skewness = 0.374). The shape of the barplot shows us how most matches are close competitions, with zero blow-outs and very few “beat-downs”, so to speak.</p>
</section>
<section id="althams-multiplicative-binomial-distribution-1" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="althams-multiplicative-binomial-distribution-1"><span class="header-section-number">5.2</span> Altham’s Multiplicative Binomial Distribution</h2>
<p>For each player in the 2024 season, use the number of legs won in each match to compute maximium likelihood estimates for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>.<br>
<strong>Note</strong>: The “for each” here can be done more efficiently with a function or a loop!</p>
<ul>
<li>Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner’s legs and sometimes from the loser’s legs.</li>
<li>Find the MLE for the player using this data. Ensure to report <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span> for each player in a nicely formatted table.<br>
<strong>Note:</strong> In Lecture on Monday, we used transformations to restrict how <code>optim()</code> searches the parameter space. For example, here, you might consider <code>p &lt;- 1/(1+exp(-par[1]))</code> and <code>theta &lt;- exp(par[2])</code>.</li>
<li>Make comments about the MLEs in the context of the standings.</li>
</ul>
<p><strong>Solution:</strong></p>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="co">#obtain unique list of player names to loop over</span></span>
<span id="cb10-2"><a href="#cb10-2"></a>players <span class="ot">=</span> <span class="fu">unique</span>(<span class="fu">c</span>(pdc.dat<span class="sc">$</span>Winner,pdc.dat<span class="sc">$</span>Loser))</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a><span class="co">#preallocated tibble to store MLE estimates</span></span>
<span id="cb10-5"><a href="#cb10-5"></a>  results <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb10-6"><a href="#cb10-6"></a>    <span class="at">Player =</span> players,</span>
<span id="cb10-7"><a href="#cb10-7"></a>    <span class="at">p =</span> <span class="cn">NA</span>,</span>
<span id="cb10-8"><a href="#cb10-8"></a>    <span class="at">theta =</span> <span class="cn">NA</span></span>
<span id="cb10-9"><a href="#cb10-9"></a>  )</span>
<span id="cb10-10"><a href="#cb10-10"></a></span>
<span id="cb10-11"><a href="#cb10-11"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(players)){</span>
<span id="cb10-12"><a href="#cb10-12"></a>  won <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb10-13"><a href="#cb10-13"></a>    <span class="fu">filter</span>(Winner<span class="sc">==</span>players[i])</span>
<span id="cb10-14"><a href="#cb10-14"></a>    <span class="co">#head(won)</span></span>
<span id="cb10-15"><a href="#cb10-15"></a>  lost <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb10-16"><a href="#cb10-16"></a>    <span class="fu">filter</span>(Loser<span class="sc">==</span>players[i])</span>
<span id="cb10-17"><a href="#cb10-17"></a>    <span class="co">#head(lost) </span></span>
<span id="cb10-18"><a href="#cb10-18"></a>  leg.counts <span class="ot">=</span> <span class="fu">c</span>(won<span class="sc">$</span>WinnerLegs, lost<span class="sc">$</span>LoserLegs)</span>
<span id="cb10-19"><a href="#cb10-19"></a></span>
<span id="cb10-20"><a href="#cb10-20"></a>  <span class="co">#building MLE</span></span>
<span id="cb10-21"><a href="#cb10-21"></a>  params <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>) <span class="co"># initial guesses</span></span>
<span id="cb10-22"><a href="#cb10-22"></a>  mle <span class="ot">=</span> <span class="fu">optim</span>(<span class="at">par=</span>params,</span>
<span id="cb10-23"><a href="#cb10-23"></a>                 <span class="at">fn=</span>llaltbinom,</span>
<span id="cb10-24"><a href="#cb10-24"></a>                 <span class="at">x=</span>leg.counts,</span>
<span id="cb10-25"><a href="#cb10-25"></a>                 <span class="at">n=</span><span class="dv">6</span>,</span>
<span id="cb10-26"><a href="#cb10-26"></a>                 <span class="at">mle=</span>T)</span>
<span id="cb10-27"><a href="#cb10-27"></a>  </span>
<span id="cb10-28"><a href="#cb10-28"></a>  p.mle <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(<span class="sc">-</span>mle<span class="sc">$</span>par[<span class="dv">1</span>]))</span>
<span id="cb10-29"><a href="#cb10-29"></a>  theta.mle <span class="ot">=</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">2</span>])</span>
<span id="cb10-30"><a href="#cb10-30"></a></span>
<span id="cb10-31"><a href="#cb10-31"></a>  results<span class="sc">$</span>p[i] <span class="ot">=</span> p.mle</span>
<span id="cb10-32"><a href="#cb10-32"></a>  results<span class="sc">$</span>theta[i] <span class="ot">=</span> theta.mle</span>
<span id="cb10-33"><a href="#cb10-33"></a>}</span>
<span id="cb10-34"><a href="#cb10-34"></a></span>
<span id="cb10-35"><a href="#cb10-35"></a>results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  Player                 p theta
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;
1 Rob Cross          0.610 0.741
2 Gerwyn Price       0.610 0.763
3 Michael Smith      0.629 0.693
4 Luke Littler       0.692 0.677
5 Michael van Gerwen 0.618 0.674
6 Luke Humphries     0.669 0.665
7 Nathan Aspinall    0.690 0.775
8 Peter Wright       0.539 0.832</code></pre>
</div>
</div>
<p></p>
<p><em>Interpretation:</em> Each value for p represents the players win probability for a given leg, therefore players with higher values for p are more likely to win legs in a given match. Theta in this context represents how each leg affects the subsequent leg. Because all players have theta values below 1, we can say that all players tend toward more balanced wins and losses/closer final scores.</p>
<p>Knowing this, we can see that Luke Littler has the highest chance of winning any given leg due to his having the highest p value. We can also observe that Luke Humphries, despite not having the highest p value, has the lowest theta value. This means that he experiences more back-and-forth leg victories and losses.</p>
<p>With regard to the standings, we find that p doesn’t 100% map to the rankings as consistently as one might expect. For example, Luke Humphries was ranked second and has a p value of 0.669, whereas Nathan Aspinall has a greater p value of 0.690 despite being ranked 5th place. Regardless, it still does a good job at roughly predicting the rankings.</p>
</section>
<section id="althams-multiplicative-beta-binomial-distribution-1" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="althams-multiplicative-beta-binomial-distribution-1"><span class="header-section-number">5.3</span> Altham’s Multiplicative Beta Binomial Distribution</h2>
<p>For each player in the 2024 season, use the number of legs won in each match to compute maxmium likelihood estimates for <span class="math inline">\(p\)</span> and <span class="math inline">\(\theta\)</span>.<br>
<strong>Note</strong>: The “for each” here can be done more efficiently with a function or a loop!</p>
<ul>
<li>Create a vector containing the number of legs won by the player. Note sometimes you will need to pull from winner’s legs and sometimes from the loser’s legs.</li>
<li>Find the MLEs for the player using this data. Ensure to report <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, and <span class="math inline">\(\theta\)</span> for each player in a nicely formatted table.<br>
<strong>Note 1</strong>: Due to the computational complexity of <code>integrate()</code>, you should compute the logged probability for <code>0:6</code> once and add them according to the data in each player’s vector. <strong>Note 2</strong>: In Lecture on Monday, we used transformations to restrict how <code>optim()</code> searches the parameter space.</li>
<li>Plot the underlying Beta(<span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>) distribution for each player.<br>
<strong>Note</strong>: Add the mean and variance of the Beta to the table of MLEs. Recall <span class="math display">\[\begin{align*}
E(X)   &amp;= \frac{\alpha}{\alpha+\beta}\\
sd(X) &amp;= \sqrt{\frac{\alpha\beta}{(\alpha+\beta)^2(\alpha+\beta+1)}}
\end{align*}\]</span></li>
<li>Make comments about the MLEs in the context of the standings.<br>
<strong>Note</strong>: The players alternate who throws first in a leg has the mathematical “head start” to reach a finish before their opponent can take another turn. Players alternate who throws first with each leg.</li>
</ul>
<p></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>llaltbbinom <span class="ot">=</span> <span class="cf">function</span>(par, x, n, <span class="at">mle=</span>F){</span>
<span id="cb12-2"><a href="#cb12-2"></a>  alpha <span class="ot">=</span>  <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">1</span>]), par[<span class="dv">1</span>])</span>
<span id="cb12-3"><a href="#cb12-3"></a>  beta <span class="ot">=</span>  <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">2</span>]), par[<span class="dv">2</span>])</span>
<span id="cb12-4"><a href="#cb12-4"></a>  theta <span class="ot">=</span>  <span class="fu">ifelse</span>(mle, <span class="fu">exp</span>(par[<span class="dv">3</span>]), par[<span class="dv">3</span>])</span>
<span id="cb12-5"><a href="#cb12-5"></a>  log.probs <span class="ot">=</span> <span class="fu">log</span>(<span class="fu">daltbbinom</span>(<span class="at">x =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">size =</span> n, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta, <span class="at">theta =</span> theta))</span>
<span id="cb12-6"><a href="#cb12-6"></a>  ll <span class="ot">=</span> <span class="fu">sum</span>(log.probs[x <span class="sc">+</span> <span class="dv">1</span>])</span>
<span id="cb12-7"><a href="#cb12-7"></a>  <span class="fu">ifelse</span>(mle, <span class="sc">-</span>ll,ll)</span>
<span id="cb12-8"><a href="#cb12-8"></a>}</span>
<span id="cb12-9"><a href="#cb12-9"></a></span>
<span id="cb12-10"><a href="#cb12-10"></a></span>
<span id="cb12-11"><a href="#cb12-11"></a><span class="co">#obtain unique list of player names to loop over</span></span>
<span id="cb12-12"><a href="#cb12-12"></a>players <span class="ot">=</span> <span class="fu">unique</span>(<span class="fu">c</span>(pdc.dat<span class="sc">$</span>Winner,pdc.dat<span class="sc">$</span>Loser))</span>
<span id="cb12-13"><a href="#cb12-13"></a></span>
<span id="cb12-14"><a href="#cb12-14"></a><span class="co">#preallocated tibble to store MLE estimates</span></span>
<span id="cb12-15"><a href="#cb12-15"></a>  results <span class="ot">=</span> <span class="fu">tibble</span>(</span>
<span id="cb12-16"><a href="#cb12-16"></a>    <span class="at">Player =</span> players,</span>
<span id="cb12-17"><a href="#cb12-17"></a>    <span class="at">alpha =</span> <span class="cn">NA</span>,</span>
<span id="cb12-18"><a href="#cb12-18"></a>    <span class="at">beta =</span> <span class="cn">NA</span>,</span>
<span id="cb12-19"><a href="#cb12-19"></a>    <span class="at">theta =</span> <span class="cn">NA</span>,</span>
<span id="cb12-20"><a href="#cb12-20"></a>    <span class="at">beta.mean =</span> <span class="cn">NA</span>,</span>
<span id="cb12-21"><a href="#cb12-21"></a>    <span class="at">beta.sd =</span> <span class="cn">NA</span></span>
<span id="cb12-22"><a href="#cb12-22"></a>  )</span>
<span id="cb12-23"><a href="#cb12-23"></a></span>
<span id="cb12-24"><a href="#cb12-24"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(players)){</span>
<span id="cb12-25"><a href="#cb12-25"></a>  won <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb12-26"><a href="#cb12-26"></a>    <span class="fu">filter</span>(Winner<span class="sc">==</span>players[i])</span>
<span id="cb12-27"><a href="#cb12-27"></a>    <span class="co">#head(won)</span></span>
<span id="cb12-28"><a href="#cb12-28"></a>  lost <span class="ot">=</span> pdc.dat <span class="sc">|&gt;</span></span>
<span id="cb12-29"><a href="#cb12-29"></a>    <span class="fu">filter</span>(Loser<span class="sc">==</span>players[i])</span>
<span id="cb12-30"><a href="#cb12-30"></a>    <span class="co">#head(lost) </span></span>
<span id="cb12-31"><a href="#cb12-31"></a>  leg.counts <span class="ot">=</span> <span class="fu">c</span>(won<span class="sc">$</span>WinnerLegs, lost<span class="sc">$</span>LoserLegs)</span>
<span id="cb12-32"><a href="#cb12-32"></a></span>
<span id="cb12-33"><a href="#cb12-33"></a>  <span class="co">#building MLE</span></span>
<span id="cb12-34"><a href="#cb12-34"></a>  params <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>) <span class="co">#initial guesses</span></span>
<span id="cb12-35"><a href="#cb12-35"></a>  mle <span class="ot">=</span> <span class="fu">optim</span>(<span class="at">par=</span>params,</span>
<span id="cb12-36"><a href="#cb12-36"></a>                 <span class="at">fn=</span>llaltbbinom,</span>
<span id="cb12-37"><a href="#cb12-37"></a>                 <span class="at">x=</span>leg.counts,</span>
<span id="cb12-38"><a href="#cb12-38"></a>                 <span class="at">n=</span><span class="dv">6</span>,</span>
<span id="cb12-39"><a href="#cb12-39"></a>                 <span class="at">mle=</span>T)</span>
<span id="cb12-40"><a href="#cb12-40"></a>  </span>
<span id="cb12-41"><a href="#cb12-41"></a>  alpha.mle <span class="ot">=</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">1</span>])</span>
<span id="cb12-42"><a href="#cb12-42"></a>  beta.mle <span class="ot">=</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">2</span>])</span>
<span id="cb12-43"><a href="#cb12-43"></a>  theta.mle <span class="ot">=</span> <span class="fu">exp</span>(mle<span class="sc">$</span>par[<span class="dv">3</span>])</span>
<span id="cb12-44"><a href="#cb12-44"></a></span>
<span id="cb12-45"><a href="#cb12-45"></a>  results<span class="sc">$</span>alpha[i] <span class="ot">=</span> alpha.mle</span>
<span id="cb12-46"><a href="#cb12-46"></a>  results<span class="sc">$</span>beta[i] <span class="ot">=</span> beta.mle</span>
<span id="cb12-47"><a href="#cb12-47"></a>  results<span class="sc">$</span>theta[i] <span class="ot">=</span> theta.mle</span>
<span id="cb12-48"><a href="#cb12-48"></a>  results<span class="sc">$</span>beta.mean[i] <span class="ot">=</span> alpha.mle <span class="sc">/</span> (alpha.mle <span class="sc">+</span> beta.mle)</span>
<span id="cb12-49"><a href="#cb12-49"></a>  results<span class="sc">$</span>beta.sd[i] <span class="ot">=</span> <span class="fu">sqrt</span>( (alpha.mle<span class="sc">*</span>beta.mle) <span class="sc">/</span> ((alpha.mle <span class="sc">+</span> beta.mle)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> (alpha.mle <span class="sc">+</span> beta.mle <span class="sc">+</span> <span class="dv">1</span>)) )</span>
<span id="cb12-50"><a href="#cb12-50"></a>}</span>
<span id="cb12-51"><a href="#cb12-51"></a></span>
<span id="cb12-52"><a href="#cb12-52"></a>results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 6
  Player             alpha  beta theta beta.mean beta.sd
  &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 Rob Cross          0.795 0.210 1.66      0.791   0.287
2 Gerwyn Price       0.892 0.260 1.64      0.774   0.285
3 Michael Smith      0.851 0.149 1.51      0.851   0.252
4 Luke Littler       1.95  0.137 1.46      0.935   0.141
5 Michael van Gerwen 0.740 0.133 1.50      0.848   0.263
6 Luke Humphries     3.02  0.425 0.978     0.877   0.156
7 Nathan Aspinall    1.89  0.215 1.64      0.898   0.172
8 Peter Wright       5.51  4.33  0.951     0.560   0.151</code></pre>
</div>
</div>
<p></p>
<p><em>Comments:</em> The mean of beta represents the average win probability. For example, Rob Cross’ average win probability is 0.791 in this model. The standard deviation of beta represents the variability of their leg winning probabilities. The standard deviations are all roughly similar, with the range being from 0.151 to 0.287. Interestingly, we see that Peter Wright, the worst ranked player and the one with the lowest beta mean, has one of the lowest beta standard deviations. Therefore, we can say that he was consistently bad.</p>
<p>Interestingly, most players in this model have theta values greater than one, indicating more momentum/interdependence between legs with each match.</p>
<p>With regard to the standings, we notice that the mean of beta also maps roughly to the rankings, with clearer differences between top and bottom players than in the regular Altham Binomial model. That is to say, players with higher mean values for beta tend to be higher in the ranking.</p>
</section>
<section id="executive-summary" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="executive-summary"><span class="header-section-number">5.4</span> Executive Summary</h2>
<p>Summarize the work you’ve done here to provide a brief (200-300 word) data-driven summary of the 2024 Premier League season using your work in Lab 10. Your summary should be professional, clear, and all claims should be corroborated with statistical support.</p>
<p><strong>Response:</strong> The 2024 PDC Premier League’s regular season took place over 16 nights, with eight of the World’s best dart players competing in best of 11 matches. With these data, we were able to count the number of legs won in each match for a given player. We first obtain a high-level numerical summary and data visualization for general information regarding the season. The median match ended with a score differential of 2, meaning a final scoreline of 6-4. This, in combination with an IQR of 2, demonstrates how many of the matches during this season were relatively close, with limited blow-out matches.</p>
<p>After obtaining this initial overview of the season, we then use the data to fit two models for identifying players’ skill levels. The first of these two models is Altham’s Multiplicative Binomial Distribution, which estimates a players per-leg win probability (<span class="math inline">\(p\)</span>) and per-match leg dependence (<span class="math inline">\(\theta\)</span>). In this model, Luke Littler had the highest win probability (<span class="math inline">\(p=0.692\)</span>) and Peter Wright had the lowest (<span class="math inline">\(p = 0.539\)</span>). However, this model was not perfect in its assessment, as 5th place Nathan Aspinall had a higher win probability. Also of note is that <span class="math inline">\(\theta &lt; 1\)</span> for all players in this model, suggesting that within each match, legs tended to be <em>negatively</em> correlated/flip-flop.</p>
<p>We then analyze the season using Altham’s Multiplicative <em>Beta</em> Binomial Distribution. In this model, <span class="math inline">\(p\)</span> is no longer fixed, but instead variable across matches. The average probabilities in this model differed significantly from before, with clearer separation between high and low-ranked players (Littler = 0.935, Wright = 0.560). Interestingly, the <span class="math inline">\(\theta\)</span> values found by this model were majority greater than 1, indicating that matches featured momentum rather than flip-flopping.</p>
<p>Despite the slightly different outcomes, the player assessments made by each model align with the 2024 PDC Premier League ranking.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>