{
  "hash": "69e2258cbebf6230f95aab5ff4af8c9b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Five-Six -- Data Wrangling in R # Title of the document\n\n# Bibliography Details\nbibliography: Lab5References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab3WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Use the pipe operator (`|>`). It makes the data wrangling tasks much easier to write.\n* Use `head(...)` or `glimpse(...)` often to ensure your code did what you wanted it to and that you haven't accidentally deleted their entire dataset with a bad filter.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n\n**Timeline**\n\n* Week of 2/16: Aim to complete the data wrangling sections\n* Week of 2/23: Aim to complete the data summaries sections\n\n# Biomedical Science Data\n\n@Kitsberg25 collect data on the Human Cytomegalovirus (HCMV). HCMV is a member of the herpesvirus family -- the same family that includes: chickenpox, mononucleosis (mono), and cold sores. Prevalence is high with a worldwide seroprevalence of 24% to 100% [@Gupta25]. The virus persists in a dormant state for the entire life of those infected. Primary cytomegalovirus infection is often asymptomatic but can present with flu-like symptoms. The infection can reactivate due to stress, aging, or a weakened immune system.\n\nThe researchers obtained blood samples from healthy donors, males and females, aged 25-45. They infected the cells of primary (human donor's blood) or THP1 (purchased cell lines) monocytes ($n = 87$ and $n = 112$, respectively) and macrophages ($n = 93$ and $n = 170$, respectively) and counted the number of viral genomes in the nuclei.\n\nNote that the original donor of the THP-1 cell line was a 1-year-old Japanese boy. He was treated for Acute Monocytic Leukemia at Tohoku Hospital Pediatrics (THP-1; the first cell line there). Because they are malignant cancer cells, they can divide indefinitely, breaking the usual cell managment that usually reigns in rogue cells. Therefore, these cells can divide indefinitely in a lab environment. THP-1 cells, and those like them, serve as such a reliable, uniform model for medical research and improve reproducability.\n\n**Preliminary Question**: Are THP-1 cells a good stand-in for human cells?\n\n**Solution:**\nThough they are not perfectly comparable to human cells, THP-1 cells are likely a good stand-in for research purposes. Though my knowledge of biology is limited, it is safe to assume that cancer cells behave differently from healthy human cells beyond just indefinite division. Furthermore, the origin of these cells lie in one unique patient, therefore they capture limited variation that occurs across the cells of different humans. However, despite these concerns, for reproducible research purposes, these cells are a good proxy for normal human cells. Their indefinite growth allows for countless experiments/studies to be run at a much much cheaper cost compared with normal cells, and the aforementioned concerns can likely be accounted for or addressed in any published research.\n\n**Research Question**: Is the virus more prevalent in the nucleus of monocytes or macrophages, explaining why HCMV stays dormant in monocytes but goes active in macrophages?\n\n## Data Wrangling\n\n### Part A \nGo to the website and download the source data [https://www.nature.com/articles/s41467-025-68063-y#Sec30](https://www.nature.com/articles/s41467-025-68063-y#Sec30).\n\nDescribe the process -- do not leave out any steps -- for how you can load the data for Figures 3b and 3d from the manuscript into `R`. \n\n**Hint**: You can use packages like `readxl` [@readxl] but you will find it substantially easier to open the `.xls` file using your computer's spreadsheet software and create a new `.csv` file with the data you need.\n\n**Solution:**\nTo accomplish this task, I opened the link provided and downloaded the source data. I then opened the data using Microsoft Excel and navigated to the tab entitled `Fig 3b`. I then appended the duplicates of each column so that there is only one column entitled \"sample\" and one column entitled \"viruses within nucleus\" I then clicked `file`, `save as`, renamed it to `\"Lab5Fig3B\"`, selected `.csv` as the format, and saved it to the my folder for Labs 5 and 6.\n\\\n\nAfter doing that, I load it in using the `tidyverse` [@tidyv] function, `read_csv()` and the full file path, skipping the blank rows.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg = read_csv(\n  \"/Users/alexvogt/Documents/GitHub/lab-5-6-data-wrangling-alvogt1020/Lab5Fig3B.csv\",\n  skip = 1\n)\n```\n:::\n\n\n \\normalsize\n\n### Part B\nThe data need to be cleaned. Note that the sample type (Healthy Donor or THP-1), cell type (Monocytes or Macrophages), and treatment (12 Hours Post-Infection or Uninfected) are all recorded in one column `sample`, separated with underscores. Use `separate(...)` from the `tidyverse` package to separate the `sample` column into the `SampleType`, `CellType`, `Treatment` columns. Save the object as `dat.kitsberg.cleaned`.\n\n**Hint**: Use `?separate(...)` to see how it works.\n\n**Solution:**\nI fill in the `separate(...)` function with the appropriate arguments to break up `sample` into multiple based on the criteria given.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg |> separate(\n  col = \"sample\",\n  into = c(\"SampleType\",\"CellType\",\"Treatment\"),\n  sep = \"_\"\n)\n\ndat.kitsberg.cleaned = dat.kitsberg.cleaned[, 1:4] # eliminate NA columns\n```\n:::\n\n\n \\normalsize\n\n### Part C\nThe researchers are only interested in observations in the treatment group (12hpi). Remove uninfected samples from the data. Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `filter(...)` function.\n\n**Solution:**\nI use the `filter(...)` function to select only observations for which `Treatment` takes on the value \"12hpi\".\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dplyr::filter(\n  dat.kitsberg.cleaned,\n  Treatment == \"12hpi\"\n)\n```\n:::\n\n\n \\normalsize\n\n### Part D\nWhen `CellType` is \"MDM\", it is a Monocyte-Derived Macrophages. That is, the cell type should be macrophages which is coded as \"mac\". Update `dat.kitsberg.cleaned` with the result.\n\n**Solution:**\nI feed dat.kitsberg.cleaned into the `mutate(...)` function, which uses a conditional statement to recode MDM in `CellType` to mac.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |>\n  mutate(\n    CellType = if_else(CellType == \"MDM\",\"mac\",CellType)\n  )\n```\n:::\n\n\n \\normalsize\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n## Part E\nThe researchers are only interested in monocytes and macrophages. Remove any other cell types. Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `filter(...)` function.\n\n**Solution:**\nI use `View(...)` to find the appropriate observation names, and the filter function from `dplyr` to rename the statements based on a logical *or* condition.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dplyr::filter(\n                                 dat.kitsberg.cleaned, \n                                 CellType %in% c(\"mac\",\"mono\")\n                                 )\n```\n:::\n\n\n \\normalsize\n\n## Part F\nClean up the data entry. Replace the shorthand the researchers used with the neat sample type (Healthy Donor or THP-1), cell type (Monocytes or Macrophages), and treatment (12 Hours Post-Infection or Uninfected). Update `dat.kitsberg.cleaned` with the result.\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n**Solution:**\n\nI use `View(...)` to see what each observation is named so that I can use a series of `if_else` statements to rename the observations.\n\nThen, I use nested `if_else(...)` statements because `SampleType` and `CellType` have two values that need to be renamed. Take `SampleType` for example: the first `if_else(...)` checks whether the value is `\"primary\"` and renames it `\"Healthy Donor\"`. The second `if_else(...)` is needed because values that are not `\"primary\"` still need to be checked to see whether they are `\"THP1\"`, and if so renames them to  `\"THP-1\"`. Any values that fail to match the conditionals remain unchanged, which includes any missing/NA values.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = dat.kitsberg.cleaned |> \n                      mutate(\n                      SampleType = if_else(SampleType == \"primary\", \"Healthy Donor\",\n                                   if_else(SampleType == \"THP1\", \"THP-1\", SampleType)),\n                      CellType = if_else(CellType == \"mono\", \"Monocytes\",\n                                 if_else(CellType == \"mac\", \"Macrophages\", CellType)),\n                      Treatment = if_else(Treatment == \"12hpi\", \"12 Hours Post-Infection\",\n                                  if_else(Treatment == \"uninfected\", \"Uninfected\",Treatment))\n                      )\n```\n:::\n\n\n \\normalsize\n\n## Part G\nIn an `R` code block, combine your answers into one code block that completes the full cleaning process. Save the object as `dat.kitsberg.cleaned`.\n\n**Note**: You will use this in the next section\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.kitsberg.cleaned = read_csv(\n  \"/Users/alexvogt/Documents/GitHub/lab-5-6-data-wrangling-alvogt1020/Lab5Fig3B.csv\",\n  skip = 1\n) |> \n\nseparate(\n  col = \"sample\",\n  into = c(\"SampleType\",\"CellType\",\"Treatment\"),\n  sep = \"_\"\n) |>\n\nselect(1:4) |> \n\ndplyr::filter(Treatment == \"12hpi\") |>\n\nmutate(\n    CellType = if_else(CellType == \"MDM\",\"mac\",CellType)\n) |>\n\ndplyr::filter(CellType == \"mac\" | CellType == \"mono\") |>\n\nmutate(\n  SampleType = if_else(SampleType == \"primary\", \"Healthy Donor\",\n                                   if_else(SampleType == \"THP1\",\"THP-1\",SampleType)),\n                       CellType   = if_else(CellType == \"mono\", \"Monocytes\",\n                                   if_else(CellType == \"mac\", \"Macrophages\", CellType)),\n                       Treatment  = if_else(Treatment == \"12hpi\", \"12 Hours Post-Infection\",\n                                   if_else(Treatment == \"uninfected\", \"Uninfected\",Treatment))\n)\n```\n:::\n\n\n \\normalsize\n\n## Data Summaries\n\n### Part A\nRecreate Figure 3b as depicted in the paper (see [https://www.nature.com/articles/s41467-025-68063-y#Fig3](https://www.nature.com/articles/s41467-025-68063-y#Fig3)). You can ignore the significance comparison because we haven't done that yet.\n\n**Hint**: I would use `geom_violin(...)` for Figure 3b I also expect your plots to look nicer -- better labels, better scaling, etc. Don't forget to use the proper formatting using the syntax in the Quarto cheatsheet.\n\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = dat.kitsberg.cleaned |> drop_na(SampleType)) + # data to plot\n    geom_violin(aes(x = CellType, \n                    y = `viruses within nucleus`),\n                fill = \"lightgrey\", alpha=0.5) +\n    geom_jitter(aes(x = CellType, \n                    y = `viruses within nucleus`),\n              width = 0.08,\n              height = 0.03) +\n    theme_bw() +\n    labs(x = \"Cell Type\",\n         y = \"HCMV Genomes in the Nucleus\")+\n    facet_wrap(~SampleType)\n```\n\n::: {.cell-output-display}\n![HCMV genomes in the nucleus for monocytes and macrophages by sample type (Healthy Donor vs THP-1).](Lab5WriteUp_files/figure-html/fig-hcmv-1.png){#fig-hcmv width=672}\n:::\n:::\n\n\n \\normalsize\n\n\n### Part B\nCompute a table containing relevant numerical summaries for Figure 3b.\n\n**Hint**: I would use `group_by(...)` and `summarize(...)` to complete this. Don't forget to use the proper formatting using `knitr::kable(...)` as described in the Quarto Cheatsheet.\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkitsberg.summary = dat.kitsberg.cleaned |>\n  group_by(SampleType, CellType) |>\n  summarize(\n    n = n(),\n    Missing = sum(is.na(`viruses within nucleus`)),\n    Mean = mean(`viruses within nucleus`, na.rm = T),\n    SD = sd(`viruses within nucleus`, na.rm = T),\n    Median = median(`viruses within nucleus`, na.rm = T),\n    IQR = IQR(`viruses within nucleus`, na.rm = T)\n  )\n```\n:::\n\n\n \\normalsize\n\n\nTo print the table nicely, we use the `knitr::kable(...)`, as suggested.\n\n\n \\normalsize\n\n\n::: {#tbl-nsum-viruscount .cell tbl-cap='HCMV Genomes in the Nucleus' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|SampleType    |CellType    |   n| Missing| Mean|   SD| Median| IQR|\n|:-------------|:-----------|---:|-------:|----:|----:|------:|---:|\n|Healthy Donor |Macrophages |  93|       0| 0.37| 0.60|      0|   1|\n|Healthy Donor |Monocytes   |  87|       0| 0.01| 0.11|      0|   0|\n|THP-1         |Macrophages | 170|       0| 0.33| 0.57|      0|   1|\n|THP-1         |Monocytes   | 112|       0| 0.04| 0.25|      0|   0|\n\n\n:::\n:::\n\n\n \\normalsize\n\nFrom the numerical summary, we see that the average amount of HCMV genomes in the nucleus is noticeably higher for macrophages than monocytes. Furthermore, macrophages exhibit much more spread with a standard deviation 3x that of monocytes. The violin plots further enrich our understanding of the results. We see that healthy donors in general exhibit more spread than THP-1 donors (which aligns with the intuitive explanation that humans are more varied than artificial cells).\n\n**Note:**\nParts C and D removed, to align with the revised version of the lab assignment.\n\n\n\n\n\n\n\n# Ship Valuation\n\n![This is a ship-shipping ship shipping shipping ships.](meme.jpg){width=80%}\n\n@ElifBal25 aim to build a model for predicting the value of Supramax and Ultramax ships using both current and past market data. Their goal was to build a model that only uses information anyone can easily look up.\n\nThe researchers collected 17 years of real ship sale prices (2005–2022), covering $n=1819$ Supramax and Ultramax ship sales.\n\n**Research Question**: Can we predict Supramax and Ultramax ship prices?\n\n## Data Wrangling\n\n### Part A\nI downloaded the data from linked in the article ([https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0319073](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0319073)). I have included the data in this lab folder as `ShipValuation-Bal25.csv`. Load the data into `R`.\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal = read_csv(\"ShipValuation-Bal25.csv\")\n```\n:::\n\n\n \\normalsize\n\n### Part B\nThe price of each Supramax and Ultramax ship is reported on the $\\log_{10}$ scale. Create a new column called `price` that contains the price in millions of dollars.\n$$\\text{Price} = \\frac{10^{\\text{SPLog}}}{1000000}$$\nSave the object as `dat.bal.cleaned`.\n\n**Hint**: I would use the `mutate(...)` function.\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal |>\n        mutate(\n          price = 10 ^ SPLog / 1000000\n        )\n```\n:::\n\n\n \\normalsize\n\n### Part C\nThe authors recorded the country that each Supramax or Ultramax ship was built in in the columns `Japan`, `China, People's Republic Of`, `Philippines`, `Korea, South`,\t`Others Country Build`. These columns are marked `1` to indicate that is the country of origin and `0` otherwise. Create a new column called `OriginCountry` that contains a clean labels for the country in which the ship was built. Update `dat.bal.cleaned` with the result.\n\n**Hint**: I would use the `mutate(...)` function. You will likely find `if_else(...)` or `case_when(...)` helpful.\n\n**Solution:**\nUsing `case_when(...)` in this instance is much easier given the amount of columns needed to scan as well as the character lengths.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    OriginCountry = case_when(\n      Japan == 1 ~ \"Japan\",\n      `China, People's Republic Of` == 1 ~ \"China\",\n      Philippines == 1 ~ \"Philippines\",\n      `Korea, South` == 1 ~ \"South Korea\",\n      `Others Country Build` == 1 ~ \"Other\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part D\nThe authors recorded each Supramax and Ultramax ship's main engine manufacturer in the columns `Caterpillar`, `MAN-B&W`, `Wartsila`, `Mitsubishi`. These columns are marked `1` to indicate that is the manufacturer and `0` otherwise. Create a new column called `Manufacturer` that contains a clean labels for the manufacturer. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous question.\n\n\n**Solution:**\n\nCopy and pasting the code from part C and adjusting it is the quickest approach for this.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    Manufacturer = case_when(\n      Caterpillar == 1 ~ \"Caterpillar\",\n      `MAN-B&W` == 1 ~ \"MAN-B&W\",\n      Wartsila == 1 ~ \"Wartsila\",\n      Mitsubishi == 1 ~ \"Mitsubishi\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part E\nThe researchers recorded whether each Supramax and Ultramax ship is currently covered by a Protection and Indemnity (P\\&I) Club. This can be an indicator that a ship meets the minimum seaworthiness and safety requirements of the insurer.\n\nThe authors recorded P&I clubs in the columns `Japan P&I Club`, `Gard`,\t`West of England`,\t`North of England`, `UK P&I`, `Britannia P&I`, `London P&I Club`, `Skuld`, `Steamship Mutual`, `Others`, `Unknown`. These columns are marked `1` to indicate that the ship is insured by that P\\&I club and `0` otherwise. Create a new column called `PI.club` that contains a clean labels for the P\\&I club. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution:**\n\nAgain, copy and pasting the code from part C and adjusting it is the quickest approach for this.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    PI.Club = case_when(\n      `Japan P&I Club` == 1 ~ \"Japan P&I Club\",\n      `Gard` == 1 ~ \"Gard\",\n      `West of England` == 1 ~ \"West of England\",\n      `North of England` == 1 ~ \"North of England\",\n      `UK P&I` == 1 ~ \"UK P&I\",\n      `Britannia P&I` == 1 ~ \"Britannia P&I\",\n      `London P&I Club`== 1 ~ \"London P&I Club\",\n      `Skuld` == 1 ~ \"Skuld\",\n      `Steamship Mutual` == 1 ~ \"Steamship Mutual\",\n      `Others` == 1 ~ \"Others\",\n      `Unknown` == 1 ~ \"Unknown\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n\n\n\n### Part F\nThe researchers recorded whether each Supramax and Ultramax ship is classed by a society that requires a ship to be safe, structurally sound, and built/maintained to specific engineering standards.\n \nThe authors recorded class society in the columns `Nippon Kaiji Kyokai (IACS)`, `Lloyd's Register`, `Bureau Veritas (IACS)`, `Det Norske Veritas (IACS)`,\t`American Bureau of Shipping (IACS)`, `Others Class`, `With Two Classes`, `Disclassed`. These columns are marked `1` to indicate that the ship is classed by that soceity and `0` otherwise. Create a new column called `Class` that contains a clean labels for the class. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution:**\n\nAgain, copy and pasting the code from part C and adjusting it is the quickest approach for this.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    Class = case_when(\n      `Nippon Kaiji Kyokai (IACS)` == 1 ~ \"Nippon Kaiji Kyokai (IACS)\",\n      `Lloyd's Register` == 1 ~ \"Lloyd's Register\",\n      `Bureau Veritas (IACS)` == 1 ~ \"Bureau Veritas (IACS)\",\n      `Det Norske Veritas (IACS)` == 1 ~ \"Det Norske Veritas (IACS)\",\n      `American Bureau of Shipping (IACS)` == 1 ~ \"American Bureau of Shipping (IACS)\",\n      `Others Class` == 1 ~ \"Others Class\",\n      `With Two Classes`== 1 ~ \"With Two Classes\",\n      `Disclassed` == 1 ~ \"Disclassed\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n### Part G\nThe researchers recorded the flag state of each Supramax and Ultramax ship. Each flag state enforces its own set of safety, environmental, and crew welfare rules and regulations. Ships under certain flag states may be more or less valuable depending on how much the flag affects the buyer's trust in the condition of the boat. \n \nThe authors recorded flag states in the columns `Panama`, `Marshall Islands`,\t`Liberia`,\t`Malta`,\t`Hong Kong`, `China`, `Singapore`, `Others Flag`, `With two flags`. These columns are marked `1` to indicate that the ship has that flag state and `0` otherwise. Create a new column called `FlagState` that contains a clean labels for the flag state. Update `dat.bal.cleaned` with the result.\n\n**Hint**: Follow the logic of the previous questions.\n\n**Solution:**\n\nAgain, copy and pasting the code from part C and adjusting it is the quickest approach for this.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = dat.bal.cleaned |>\n  mutate(\n    FlagState = case_when(\n      `Panama` == 1 ~ \"Panama\",\n      `Marshall Islands` == 1 ~ \"Marshall Islands\",\n      `Liberia` == 1 ~ \"Liberia\",\n      `Malta` == 1 ~ \"Malta\",\n      `Hong Kong, China` == 1 ~ \"Hong Kong\",\n      `Singapore` == 1 ~ \"Singapore\",\n      `Others Flag` == 1 ~ \"Others Flag\",\n      `With two flags`== 1 ~ \"With two flags\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n## Part H\nIn an `R` code block, combine your answers into one code block that completes the full cleaning process. Save the object as `dat.bal.cleaned`.\n\n**Note**: You will use this in the next section\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat.bal.cleaned = read_csv(\"ShipValuation-Bal25.csv\") |>\n\nmutate(\n  price = 10 ^ SPLog / 1000000\n) |>\n\nmutate(\n    OriginCountry = case_when(\n      Japan == 1 ~ \"Japan\",\n      `China, People's Republic Of` == 1 ~ \"China\",\n      Philippines == 1 ~ \"Philippines\",\n      `Korea, South` == 1 ~ \"South Korea\",\n      `Others Country Build` == 1 ~ \"Other\",\n      TRUE ~ NA\n    )\n  ) |>\n\nmutate(\n    Manufacturer = case_when(\n      Caterpillar == 1 ~ \"Caterpillar\",\n      `MAN-B&W` == 1 ~ \"MAN-B&W\",\n      Wartsila == 1 ~ \"Wartsila\",\n      Mitsubishi == 1 ~ \"Mitsubishi\",\n      TRUE ~ NA\n    )\n  ) |>\n\nmutate(\n    PI.Club = case_when(\n      `Japan P&I Club` == 1 ~ \"Japan P&I Club\",\n      `Gard` == 1 ~ \"Gard\",\n      `West of England` == 1 ~ \"West of England\",\n      `North of England` == 1 ~ \"North of England\",\n      `UK P&I` == 1 ~ \"UK P&I\",\n      `Britannia P&I` == 1 ~ \"Britannia P&I\",\n      `London P&I Club`== 1 ~ \"London P&I Club\",\n      `Skuld` == 1 ~ \"Skuld\",\n      `Steamship Mutual` == 1 ~ \"Steamship Mutual\",\n      `Others` == 1 ~ \"Others\",\n      `Unknown` == 1 ~ \"Unknown\",\n      TRUE ~ NA\n    )\n  ) |>\n\nmutate(\n    Class = case_when(\n      `Nippon Kaiji Kyokai (IACS)` == 1 ~ \"Nippon Kaiji Kyokai (IACS)\",\n      `Lloyd's Register` == 1 ~ \"Lloyd's Register\",\n      `Bureau Veritas (IACS)` == 1 ~ \"Bureau Veritas (IACS)\",\n      `Det Norske Veritas (IACS)` == 1 ~ \"Det Norske Veritas (IACS)\",\n      `American Bureau of Shipping (IACS)` == 1 ~ \"American Bureau of Shipping (IACS)\",\n      `Others Class` == 1 ~ \"Others Class\",\n      `With Two Classes`== 1 ~ \"With Two Classes\",\n      `Disclassed` == 1 ~ \"Disclassed\",\n      TRUE ~ NA\n    )\n  ) |>\n\nmutate(\n    FlagState = case_when(\n      `Panama` == 1 ~ \"Panama\",\n      `Marshall Islands` == 1 ~ \"Marshall Islands\",\n      `Liberia` == 1 ~ \"Liberia\",\n      `Malta` == 1 ~ \"Malta\",\n      `Hong Kong, China` == 1 ~ \"Hong Kong\",\n      `Singapore` == 1 ~ \"Singapore\",\n      `Others Flag` == 1 ~ \"Others Flag\",\n      `With two flags`== 1 ~ \"With two flags\",\n      TRUE ~ NA\n    )\n  )\n```\n:::\n\n\n \\normalsize\n\n\n\n## Data Summaries\nFirst, I provide a short description of the other variables in their data. Note that the size ordering of types of ships discussed below is:\n\n$$\\text{Handysize} < \\text{Supramax} < \\text{Ultramax} < \\text{Panamax} < \\text{Capesize}$$\n\n* `DWT`: The deadweight tonnage, which is the maximum weight each Supramax and Ultramax ship can safely carry in metric tons. This gives a measure of how much cargo, fuel, fresh water, ballast water, provisions, and crew a ship can handle. \n* `Yas`: The age in years. New Supramax and Ultramax ships were recorded as having age 1.\n* `Enginges RPM`: Revolutions per minute of each Supramax and Ultramax ship's main propulsion engine. Generally speaking, lower-RPM engines are more expensive because they are more fuel efficient.\n* `BACI`: The Baltic Capesize Index. This describes freight rates for Capesize dry bulk ships, which reflects supply and demand. When BACI is high, Capesize ships are more profitable in shipping, which could positively affect Supramax and Ultramax ship values as demand for dry bulk commodities might be high and large shipments could be split into several Supramax and Ultramax shipments.\\\n**Note**: This reports the current BACI. The data also contain the BACI form 1, 2, and 3 months before the sale (`BACI-1`, `BACI-2`, `BACI-3`).\n* `BPNI`: The Baltic Panamax Index. This describes the cost to ship dry bulk commodities (e.g., coal or grain) on Panamax class ships. When BPNI is high, we expect Panamax ship prices to go up. Supramax and Ultramax ship values tend to follow this trend as charterers switch to these smaller vessels when Panamax rates become too expensive.\\\n**Note**: This reports the current BPNI. The data also contain the BPNI form 1, 2, and 3 months before the sale (`BPNI-1`, `BPNI-2`, `BPNI-3`).\n* `BSIS`: The Baltic Supramax Index. This describes freight rates for Supramax vessels, which reflects supply and demand. When BSIS is high, Supramax and Ultramax prices are usually higher because they are more profitable in shipping.\\\n**Note**: This reports the current BSIS. The data also contain the BSIS form 1, 2, and 3 months before the sale (`BSIS-1`, `BSIS-2`, `BSIS-3`).\n* `BHSI`: The Baltic Handysize Index. This describes freight rates for handysize vessels. When BHSI is high, Supramax and Ultramax ship prices are usually higher because the prices move together.\\\n**Note**: This reports the current BHSI. The data also contain the BHSI form 1, 2, and 3 months before the sale (`BHSI-1`, `BHSI-2`, `BHSI-3`).\n* `LIBOR`: The London InterBank Offered Rate. This describes the average reported interest rate at which banks would lend US dollars for 3 months.\n \n\n### Part A\nChoose a categorical variable. Create a plot and corresponding numerical summary to assess whether or how ship prices vary across the levels of the selected categorical variable.  \n\n**Solution:**\nFor the visualization of any categorical variable, I choose to analyze the variable `OriginCountry`. I use a box plot to compare price across categories.\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat.bal.cleaned |> drop_na(OriginCountry, price)) +\n  geom_boxplot(aes(x = OriginCountry,\n                   y = price)) +\n  theme_bw() +\n  labs(x = \"Country of Origin\",\n       y = \"Price (Millions of $)\") +\n  ggtitle(\"Ship Price by Country of Origin\")\n```\n\n::: {.cell-output-display}\n![Ship price by country of origin.](Lab5WriteUp_files/figure-html/fig-ship-price-origin-1.png){#fig-ship-price-origin width=672}\n:::\n:::\n\n\n \\normalsize\n\nI then produce a corresponding numerical summary:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbal.summary = dat.bal.cleaned |>\n  drop_na(OriginCountry, price) |>\n  group_by(OriginCountry) |>\n  summarize(\n    n = n(),\n    `Missing Price` = sum(is.na(price)),\n    `Mean Price` = mean(price, na.rm = TRUE),\n    `SD Price` = sd(price, na.rm = TRUE),\n    `Median Price` = median(price, na.rm = TRUE),\n    `IQR Price` = IQR(price, na.rm = TRUE)\n  )\n\nknitr::kable(bal.summary)\n```\n\n::: {.cell-output-display}\n\n\n|OriginCountry |   n| Missing Price| Mean Price|  SD Price| Median Price| IQR Price|\n|:-------------|---:|-------------:|----------:|---------:|------------:|---------:|\n|China         | 613|             0|   16.80350| 10.391663|        14.50|    10.650|\n|Japan         | 898|             0|   16.86071| 11.846689|        14.20|    13.700|\n|Other         | 103|             0|   11.80471|  7.375389|         9.40|     8.417|\n|Philippines   | 130|             0|   17.07369| 10.255985|        14.35|    10.875|\n|South Korea   |  75|             0|   14.63958| 10.316007|        11.20|    11.450|\n\n\n:::\n:::\n\n\n \\normalsize\n\nFrom the numerical summary, we see that the Phillipines has the highest mean price (around 17 million dollars), followed by Japan and China (16.86 and 16.8 million dollars respectively). Countries that fall under other have a noticeably lower average price of around 11.8 million dollars. The median prices are more similar than the means, though \"other\" countries and South Korea have very low medians (9.4 and 11.2 million dollars respectively).\n\nWe can also see that Japan has the highest variability in terms of standard deviation and IQR, with \"other\" countries showing the least variability.\n\n\n\n### Part B\nChoose a quantitative variable. Create a plot and corresponding numerical summary to assess whether or how ship prices vary with the selected quantitative variable.\n\n**Solution:**\nFor the visualization of any quantitative/continuous variable, I choose to analyze the variable `LIBOR`, which reports the average interest rate at which banks would lend US dollars for 3 months. I use a scatterplot to visualize the relationship between this and price.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dat.bal.cleaned) +                     \n  geom_point(aes(x = `LIBOR`,                 \n                 y =  price), alpha = 0.3) +   \n  geom_smooth(aes(x = `LIBOR`,                \n                  y = price),                 \n              method = \"lm\",                  \n              color = \"black\") +              \n  theme_bw() +                                \n  labs(x = \"London InterBank Offered Rate (LIBOR)\",         \n       y = \"Price (Millions of $)\") +\n  ggtitle(\"Price against LIBOR\")                            \n```\n\n::: {.cell-output-display}\n![](Lab5WriteUp_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n \\normalsize\n\nNote that an alpha of 0.3 is specified to add transparency to our points. This helps tackle the problem of densely concentrated data (particulary close to 0.00).\n\nTo create the numerical summary, we use the code below:\n\n\n \\normalsize\n\n\n::: {#tbl-libor-summary .cell tbl-cap='Ship Price vs LIBOR in Ship Valuation Data' tbl-align='center'}\n::: {.cell-output-display}\n\n\n|    n| Missing LIBOR| Missing Price| Correlation| Mean LIBOR| SD LIBOR| Mean Price| SD Price|\n|----:|-------------:|-------------:|-----------:|----------:|--------:|----------:|--------:|\n| 2019|           200|           200|    0.323471|  0.0149213| 0.015402|   16.47878| 11.04333|\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe can see that there is a weak, positive, linear correlation between LIBOR and ship price (corr = 0.323471). The scatterplot shows that most observations occur with LIBOR values close to 0 (`mean LIBOR` = .0149213). The average price of ships from this dataset is around 16.5 million dollars, with a significant amount of spread (SD = 11.04333).",
    "supporting": [
      "Lab5WriteUp_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}