{
  "hash": "02072f87c963cfb9ea80c32a43895e70",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Point Estimation - A Comprehensive Review # Title of the document\n\n# Bibliography Details\nbibliography: ExamReview.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n# Introduction and Background\n\nPoint estimation is a fundamental skill in the statistician's toolbox. Formally, we define a point estimator $\\hat{\\theta}(X) = \\hat{\\theta}(X_1, X_2, \\dots, X_n)$ as any function of the sample $X$. We use such functions to obtain point estimates, $\\hat{\\theta}(x) = \\hat{\\theta}(x_1, x_2, \\dots, x_n)$, which are realized values from a point estimator. One might wonder how this applies to practical statistical analysis.\n\n\nOften when conducting statistical analysis, we do not have information regarding the entire population of interest. As such, we must rely on the available data to estimate the true population parameters. To do this, we compute statistics, or functions of the observed data such as the sample mean, and use them as our parameter estimates. Because statistics are functions of the sample, they are, by definition, point estimators. \n\nThe two methods for point estimation that we covered in MATH240 are (i) Method of Moments and (ii) Maximum Likelihood Estimation. In short, Method of Moments estimation matches sample moments to population moments, while Maximum Likelihood Estimation finds the parameters that maximize the likelihood of observing the existing data.\n\n## Example - Heart Failure Survival Times\nTo demonstrate each procedure, we will work with data from a study on heart failure survival times from @ahmad2017.    \n\n### Method of Moments\nThe first step in point estimation is identifying an appropriate distribution for the population. The variable of interest in this study is survival time, which naturally guides us toward the exponential distribution. Something to note is that the exponential distribution is best used for events that occur at a constant average rate, and this study notes that mortality is not constant throughout time. Regardless, other features of the data such as right-skewness, strictly positive values, and time-to-event analysis make the exponential distribution a reasonable fit for the data.  \n\nNow that we have a distribution in mind, we can note what parameter(s) shape the distribution and begin estimating. The exponential distribution is parameterized by the rate parameter $\\lambda$. $\\lambda$ in this context can be thought of as the average rate at which patients die. The expected value of a population that follows the exponential distribution is: $$E(X) = \\frac{1}{\\lambda}$$\n\n\nWith this information under our belt, we can begin with our Method of Moments estimate for $\\lambda$.\n\nAs we previously mentioned, the Method of Moments estimates parameters by matching sample moments to population moments. For an exponential distribution, the first population moment is\n\n$$\nE(X) = \\frac{1}{\\lambda}.\n$$\n\nThe first sample moment is the sample mean, $\\bar{X}$. \n\nBecause we only have one unknown parameter to solve for, this one equation is enough. It is worth noting that in general, the number of equations we need to obtain our Method of Moments estimates is equal to the number of parameters. Here, solving for $\\lambda$ with the first population and sample moments gives the Method of Moments estimator:\n\n$$\n\\bar{X} = \\frac{1}{\\lambda}.\n$$\n\n\n$$\n\\hat{\\lambda}_{MOM} = \\frac{1}{\\bar{X}}.\n$$\n\nWe can solve this computationally in `R` below:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read in the data\nheart.dat = read_csv(\"heart_failure_data.csv\")\n\nx = heart.dat$TIME # pull the variable of interest from the data \n(lambda.mom = 1 / mean(x, na.rm = T)) # solve for the point estimate\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007676903\n```\n\n\n:::\n\n```{.r .cell-code}\n(expected.value.mom = 1 / lambda.mom) # find the expected value using lambda hat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 130.2609\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThus, our Method of Moments estimate is $\\hat{\\lambda}_{MOM} \\approx 0.007676903.$ We interpret this directly as the estimated daily death rate (because survival time is measured in days), and can plug that value back in to our expected value formula to find the expected survival time, $$E(X) = \\frac{1}{\\hat{\\lambda}_{MOM}} \\approx 130.2609 \\text{ days}.$$\n\n## Maximum Likelihood Estimation\nA more robust method for point estimation is Maximum Likelihood Estimation. This involves finding the parameter estimate that maximizes the likelihood function, $$L(\\theta \\mid x) = \\prod_{i=1}^n f_X(x_i \\mid \\theta).$$\n\nIn other words, we find the parameter estimate that maximizes the probability of observing the existing data. In practice, we often maximize the log-likelihood function, allowing us to work with sums instead of products. This does not change our final estimate because of the natural log's monotonicity:\n\n$$\\ell(\\theta \\mid x) = \\ln\\left(L(\\theta \\mid x)\\right)\n= \\ln\\left(\\prod_{i=1}^n f_X(x_i \\mid \\theta)\\right)\n= \\sum_{i=1}^n \\ln\\left(f_X(x_i \\mid \\theta)\\right)$$\n\nWe can solve this computationally using `R`'s `optim()` function to find the minimum of $-\\ell(\\theta \\mid x)$:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nllexp = function(par, data, neg=F){\n  lambda = par[1]\n\n  ll = sum(log(dexp(x = data, rate = lambda)))\n  ifelse(neg, -ll, ll)\n}\n\nmll = optim(par = lambda.mom, # use the MoM estimate as initial guess for this example\n              fn = llexp,\n              data = x,\n              neg = T, # minimizing\n)\n\n(lambda.mle = mll$par)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007676903\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\nFrom Maximum Likelihood Estimation, we obtain the same value, $\\hat{\\lambda}_{MLE} \\approx 0.007676903.$ The fact that MLE and MOM provide identical estimates is because of the exponential distribution's particular likelihood function and optimization, though that is not the focus of this exercise (extended explanation can be found at the bottom of this page).\n\n## Evaluating the Estimator Using Simulation\n\nWe have three primary measures for how reliable an estimator is: (i) bias, (ii) precision, and (iii) mean squared error (MSE).   \n\n$\\text{Bias}_\\theta(\\hat{\\theta}) = E(\\hat{\\theta}-\\theta)$ measures the average error of the point estimate. When bias is equal to or sufficiently close to 0, we call the estimate unbiased.  \n\n$\\text{Precision}_\\theta(\\hat{\\theta}) = 1/\\text{var}_\\theta(\\hat{\\theta})$ measures how much an estimator varies across repeated samples. Higher precision is preferable to lower precision.  \n\n$\\text{MSE}_\\theta(\\hat{\\theta}) = E_\\theta\\left[(\\hat{\\theta} - \\theta)^2\\right] \n= \\text{var}_\\theta(\\hat{\\theta}) + \\left(E_\\theta(\\hat{\\theta}) - \\theta\\right)^2 \n= \\text{var}_\\theta(\\hat{\\theta}) + \\text{Bias}_\\theta(\\hat{\\theta})^2$ is a more comprehensive metric that considers both accuracy and precision.  \n\nWe can evaluate the MOM/MLE estimator for the exponential distribution by computing these values for a simulated dataset with a known $\\lambda$, taking many samples to generate point estimates for this true $\\lambda$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(394787)\n\nlambda.true = lambda.mle\nn = 50\nn.simulations = 1000\n\nlambda.hat = numeric(n.simulations)\n\nfor(i in 1:n.simulations){\n  sim.data = rexp(n, rate = lambda.true) #create simulated data with the true lambda equal to our estimated lambda\n  lambda.hat[i] = 1 / mean(sim.data) # apply estimator to simulated data\n}\n\nbias = mean(lambda.hat) - lambda.true\nvariance = var(lambda.hat)\nprecision = 1 / variance\nmse = bias^2 + variance\n\ntibble(\n  Bias = bias,\n  Precision = precision,\n  MSE = mse\n) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|      Bias| Precision|     MSE|\n|---------:|---------:|-------:|\n| 0.0001513|  793190.6| 1.3e-06|\n\n\n:::\n:::\n\n\n \\normalsize\n\nFrom our simulation, we see that even for a modest sample size of $n=50$, the estimator is close enough to 0 to be considered unbiased, and features high precision and negligible MSE. This all indicates that the estimator is very accurate on average and does not vary much across repeated samples. This is important information to have, because we only obtain one estimate from our sample in practice and thus need to know how reliable it is.\n\n\n### Why Do MOM and MLE Provide the Same Estimates for the Exponential Distribution?\nThe likelihood function for the exponential distribution is as follows: \n$$L(\\lambda) = \\prod_{i=1}^n \\lambda e^{-\\lambda x_i}\n= \\lambda^n e^{-\\lambda \\sum_{i=1}^n x_i}\n$$\n\nTaking the natural log of this function yields:\n$$\n\\ell(\\lambda) = \\ln L(\\lambda)\n= n \\ln(\\lambda) - \\lambda \\sum_{i=1}^n x_i\n$$\n\nWe then take the derivative and set it equal to 0, finding the value of $\\hat{\\lambda}$ that satisfies the equation:\n$$\n\\frac{d\\ell}{d\\lambda} = \\frac{n}{\\lambda} - \\sum_{i=1}^n x_i\n$$\n\n$$\n\\frac{n}{\\lambda} = \\sum_{i=1}^n x_i\n\\quad \\Rightarrow \\quad\n\\hat{\\lambda}_{MLE} = \\frac{n}{\\sum_{i=1}^n x_i} = \\frac{1}{\\bar{X}}$$\n\nTherefore, the Maximum Likelihood procedure for the exponential distribution yields the same estimator as the Method of Moments",
    "supporting": [
      "ExamReview_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}