{
  "hash": "c6b732ce5177a833ebb4a57b18d3900d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Lab Eight -- Probability # Title of the document\n\n# Bibliography Details\nbibliography: Lab8References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab8WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n**Tips**\n\n* Complete the tasks below. Make sure to start your solutions in on a new line that starts with \"**Solution**:\".\n* Make sure to use the Quarto Cheatsheet. This will make completing and writing up the lab *much* easier.\n* Make sure to use \"enter\" to make your code readable, so it doesn't run off the page. I switched the Quarto document to automatically render to .pdf, so you can see what you're submitting by default. You can switch back for the highlighting by moving the html block above the pdf block in the YAML header.\n* Don't forget that you can copy-and-paste code when you're doing something similar as we did in class!\n* Make sure to plot all computed probabilities. This is good `ggplot` practice AND will help make sure you don't make a mistake when computing the probability.\n\n# The Binomial and Negative Binomial Distributions\n\n## The Binomial Distribution\nIn many introductory courses, we make the simplifying assumption of independence in Bernoulli trials. For example, when playing best two-out-of-three legs in a darts match, we would assume Player A has an 70% chance of winning each leg. We write:\n$$X \\sim \\text{Binomial}(n=3, p=0.70)$$\nwhere\n\n* $X$ is the number of legs won\n* $n$ is the number of trials \n* $p$ is the probability of the event of interest\n\nOf note, it is not necessarily the case that the players play all three legs -- if either player wins legs one and two the match ends.\n\nThere are eight possible outcomes for Player A:\n\n* (win, win, \"win\") $\\longrightarrow$ Player A wins\n* (win, win, \"lose\") $\\longrightarrow$ Player A wins\n* (win, lose, win) $\\longrightarrow$ Player A wins\n* (win, lose, lose) $\\longrightarrow$ Player A loses\n* (lose, win, win)  $\\longrightarrow$ Player A wins\n* (lose, win, lose) $\\longrightarrow$ Player A loses\n* (lose, lose, \"win\") $\\longrightarrow$ Player A loses\n* (lose, lose, \"lose\") $\\longrightarrow$ Player A loses\n\n**Note**: I use quotations above to denote outcomes where the last match isn't actually played.\n\n**Use the Binomial distribution to compute the probability that Player A wins the match.  Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution:**\nTo find the probability that Player A wins the match, we use the binomial distribution: $$X \\sim \\text{Binomial}(n=3, p=0.70)$$ where $X$ is the number of  legs won, and $X \\ge 2$ denotes a match being won. We subtract the CDF for $X \\leq 1$ from 1 to obtain this result computationally.\n\n$$P(\\text{A wins}) = P(X \\ge 2) =  1 - P(X \\le 1) = 1 - F(1)$$\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1- pbinom(q = 1, prob = 0.7, size = 3) # P(X >= 2 |n=3, p=0.7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe can visualize this probability with both a PMF and CDF graph:\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 3\np = 0.7\nggdat = tibble(x = 0:3) |>\n  mutate(PMF = dbinom(x, n, p),\n         CDF = pbinom(x, n, p))\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                aes(x = x, ymin = 0, ymax = PMF)) +\n  geom_linerange(data = ggdat |> filter(x>=2),\n                aes(x = x, ymin = 0, ymax = PMF),\n                color = \"darkorchid2\", linewidth=5, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:3) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_step(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat |> filter(x==1),\n             aes(x = x, y = CDF),\n             color=\"darkorchid2\", size=5, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:10) +\n  ylab(\"Cumulative Probability\") +\ntheme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![PMF and CDF for X ~ Binomial(3, 0.7), highlighting P(X ≥ 2).](Lab8WriteUp_files/figure-pdf/fig-binomial-pmf-cdf-1.pdf){#fig-binomial-pmf-cdf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Negative Binomial Distribution\nIn intermediate courses, we learn the Negative Binomial distribution that we use to model the number of \"failures\" until the $r$th success. Note that this approach still makes the simplifying assumption of independence in Bernoulli trials.\n\n**Specify the two cases necessary to compute the probability. Fully explain these probability statements in the context of a best two-out-of-three match and the Negative Binomial distribution. Finally, compute the probability that Player A wins the match and show you get the same result as the Binomial approach. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution:**\nThe two cases are *(a)* winning the first two games (WW) or *(b)* losing one game (WLW, LWW). For case *(a)*, the probability statement would use the negative binomial distribution to compute the probability of 0 failures before the players 2nd victory, for case *(b)*, the probability statement would use the negative binomial distribution to compute the probability of 1 failure before the players 2nd victory.\n\nWe sum these two probability statements to find the total probability of success using the Negative Binomial Distribution: \n\n$$P(X \\le 1) = P(X=0) + P(X=1)$$\n\n$$X \\sim \\text{NegBinomial}(r=2, p=0.70)$$\nWhere X is the number of losses before the player achieves their second win.\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr = 2\np = 0.7\ndnbinom(0, r, p) + dnbinom(1, r, p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.784\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr = 2\np = 0.7\nggdat = tibble(x = 0:3) |>\n  mutate(PMF = dnbinom(x,r,p),\n         CDF = pnbinom(x, r,p))\n\nPMF.plot = ggplot() +\n  geom_linerange(data = ggdat,\n                 aes(x = x, ymin = 0, ymax = PMF)) +\n\n  geom_linerange(data = ggdat |> filter(x<=1),\n                aes(x = x, ymin = 0, ymax = PMF),\n                color = \"forestgreen\", linewidth=5, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:10) +\n  ylab(\"Probability\") +\n  theme_bw()\n\nCDF.plot = ggplot() +\n  geom_step(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat, aes(x = x, y = CDF)) +\n  geom_point(data=ggdat |> filter(x==1),\n             aes(x = x, y = CDF),\n             color=\"forestgreen\", size=5, alpha=0.50) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(\"x\", breaks=0:10) +\n  ylab(\"Cumulative Probability\") +\n  theme_bw()\n\nPMF.plot | CDF.plot\n```\n\n::: {.cell-output-display}\n![PMF and CDF for X ~ NegBinomial(2, 0.7), highlighting P(X ≤ 1).](Lab8WriteUp_files/figure-pdf/fig-negbinom-pmf-cdf-1.pdf){#fig-negbinom-pmf-cdf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n# The Beta Binomial Distribution\nOne approach to generalize this modeling is to use a Beta-Binomial distribution. This distribution arrises when we let $p$ be a random variable that follows a Beta distribution:\n\\begin{align*}\n  P &\\sim \\text{Beta}(\\alpha, \\beta)\\\\\n  X &\\sim \\text{Binomial}(n, P).\n\\end{align*}\nThis distribution is not part of base `R`, but is available using the `_bbinom` functions from the `extraDistr` package [@extraDistr].\n\nThe primary benefit is that the Beta-Binomial enables us to specify some uncertainty about the skill of Player A, as $p$ does not have to be fixed (e.g., $p=0.70$). Suppose the result of the best two-out-of-three match follows a Beta-Binomial distribution  where $\\alpha=7$ and $\\beta=3$.\n\n## The Beta Part\n1. **Plot the corresponding Beta distribution. Interpret the plot in the context of a best two-out-of-three match and the Binomial distribution.**\\\n**Hint**: The Beta distribution is available in base `R` via `_beta()`.\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\na = 7\nb = 3\ndat = tibble(x = seq(0, 1, 0.001)) |>\n  mutate(PDF = dbeta(x, a, b)\n  )\n```\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n  ggplot() +\n    geom_line(aes(x = x,\n                  y = PDF)) +\n    geom_hline(yintercept = 0) +\n    xlab(\"p (win probability)\") +\n    ylab(\"Density\") +\n    theme_bw()\n```\n\n::: {.cell-output-display}\n![Beta(7,3) distribution showing uncertainty in win probability.](Lab8WriteUp_files/figure-pdf/fig-beta-density-1.pdf){#fig-beta-density fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. How does the Beta incorporate uncertainty about the skill of Player A? **Compute the mean and variance of the distribution.**\\\n**Hint**: You will find the `integrate(...)` function helpful here. \n\\begin{align*}\n  E(P) &= \\mu_P = \\int_{0}^1 p f_P(p) dp\\\\\n  var(P) &= \\sigma^2_P = \\int_{0}^1 (p-\\mu_P)^2 f_P(p) dp\\\\\n\\end{align*}\n\n**Solution:**\nBeta incorporates uncertainty about the skill of player A by making the probability, $p$, a random variable that follows the beta distribution, instead of the parameter being a fixed probability. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\na = 7\nb = 3\nmu.integrand = function(p) {(p * dbeta(p,a,b))}\n(mu = integrate(mu.integrand, lower = 0, upper = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.7 with absolute error < 7.8e-15\n```\n\n\n:::\n\n```{.r .cell-code}\nvar.integrand = function(p) {((p - mu$value)^2 * dbeta(p,a,b))}\n(var = integrate(var.integrand, lower = 0, upper = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.01909091 with absolute error < 2.1e-16\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the probability that Player A has a win probability of exactly 0.70?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\\\n**Hint:** Think carefully about the properties of continuous distributions here.\n\n**Solution:**\nThe probability of a continuous random variable taking on a specific value is 0. Formally, we say: $$P(X=x) = 0$$ for continuous random variables. Therefore, we say that the probability of Player A having a win probability of exactly 0.70, $$P(P=0.70) = 0$$ For this reason, PMFs do not exist for continous random variables. However, we can demonstrate the idea by choosing a small window around $p = 0.7$ and computing the in-between probability using CDFs.\n\n$$P(P=0.7) \\approx P(0.699999 \\le P \\le 0.700001) = F_P(0.700001) - F_P(0.699999)$$\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\na = 7\nb = 3\npbeta(0.700001,a,b) - pbeta(0.699999,a,b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.336559e-06\n```\n\n\n:::\n:::\n\n\n \\normalsize\nThe output, $\\approx 5.34 \\times 10^{-6}$ is, as expected, very close to 0.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = seq(0,1,0.001)\ndat = tibble(\n  x = x,\n  PDF = dbeta(x,a,b)\n)\n```\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n    ggplot() +\n      geom_line(aes(x = x,\n                    y = PDF)) +\n      geom_hline(yintercept = 0) +\n      geom_vline(xintercept = 0.7, color=\"darkorchid2\") +\n      theme_bw() +\n      xlab(\"p (win probability)\") +\n      ylab(\"Density\")\n```\n\n::: {.cell-output-display}\n![Density of Beta(7,3) with vertical line at p = 0.7.](Lab8WriteUp_files/figure-pdf/fig-beta-point-1.pdf){#fig-beta-point fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nRemember that the area under the PDF corresponds to probability. When we look at the area under the curve for a single point, we are attempting to find the area of a line (which is illustrated by the dark orchid line at $p=0.7$). The area of a line is 0, thus confirming what we know about continous random variables.\n\n\n1. **What is the probability that Player A has a win probability of at least 0.50?  Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the probability using `ggplot`.**\n\nTo do this, we simply use the CDF. $$P(P \\ge 0.50) = 1 - P(P \\le 0.50)$$\n$$ = 1 - F_{P}(0.50)$$\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\na = 7\nb = 3\n1 - pbeta(0.5,a,b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9101562\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nWe plot this below:\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = seq(0,1,0.001)\ndat = tibble(\n  x = x,\n  CDF = pbeta(x,a,b)\n)\n```\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n    ggplot() +\n      geom_line(aes(x = x,\n                    y = CDF)) +\n      geom_point(aes(x = 0.5, y = pbeta(0.5, 7, 3)),\n               color = \"darkgoldenrod2\", size = 2) +\n      geom_hline(yintercept = pbeta(0.5, 7, 3),\n                 color = \"darkgoldenrod2\") +\n      geom_hline(yintercept = 0) +\n      theme_bw() +\n      xlab(\"p (win probability)\") +\n      ylab(\"Cumulative Probability\")\n```\n\n::: {.cell-output-display}\n![CDF of Beta(7,3), highlighting probability that p ≥ 0.5.](Lab8WriteUp_files/figure-pdf/fig-beta-cdf-1.pdf){#fig-beta-cdf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n1. **What is the 90th percentile of Player A's win probability based on this Beta distribution? Make sure write out your probability statement and work to write it in terms of the distribution function (PDF/CDF) to plot the percentile using `ggplot`.**\n\n**Solution**\nWe calculate the 90th percentile of Player A's win probability by using the inverse CDF function with $p = 0.90$. The written-out probability statement is as follows:\n\n$$P(P \\le p) = 0.90$$\n\n$$F_P(p) = 0.90$$\n\n$$p = F_P^{-1}(0.90)$$\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\na = 7\nb = 3\nqbeta(0.9,a,b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8705027\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = seq(0,1,0.001)\ndat = tibble(\n  x = x,\n  CDF = pbeta(x,a,b)\n)\n```\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat |>\n    ggplot() +\n      geom_line(aes(x = x,\n                    y = CDF)) +\n      geom_point(aes(x = qbeta(0.9, a, b), y = 0.9),\n           color = \"darkgoldenrod2\") +\n      geom_hline(yintercept = 0) +\n      geom_hline(yintercept = 0.9, color = \"darkgoldenrod2\") +\n      theme_bw() +\n      xlab(\"p (win probability)\") +\n      ylab(\"Cumulative Probability\")\n```\n\n::: {.cell-output-display}\n![CDF of Beta(7,3) showing the 90th percentile.](Lab8WriteUp_files/figure-pdf/fig-beta-quantile-1.pdf){#fig-beta-quantile fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Beta-Binomial Part\n**Compute the probability that Player A wins the match. Compare your result to the Binomial and Negative Binomial results. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`**\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(extraDistr)\n1 - pbbinom(q=1, size=3, alpha = 7, beta = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7636364\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe probability of winning is slightly lower in the Beta-Binomial model (0.7636364 < 0.784). This is because the Beta-Binomial model assumes the player's win probability is not fixed at 0.7, but that it is variable. The answers we obtain suggest that the lower match-winning probabilities drag the overall probability of winning a best-two-out-of-three down more than their higher counterparts.\n\n## The Why\nCheck the expected value and variance of each distribution.\n\nAnalytically, we have\n\\begin{align*}\n  E(X) &= np  &&var(X) = np(1-p) \\tag{Binomial Distribution}\\\\\n  E(X) &= n\\left(\\frac{\\alpha}{\\alpha+\\beta}\\right)  &&var(X) = \\frac{n \\alpha \\beta (\\alpha + \\beta + n)}{(\\alpha+\\beta)^2(\\alpha + \\beta + 1)} \\tag{Beta-Binomial Distribution}\n\\end{align*}\n\n**For each distribution, compute the mean number of legs won for player A.**\\\n**Hint**: You can perform the sum over the finite support set here. \n\\begin{align*}\n  E(X)   = \\mu_X    &= \\sum_{i=0}^3 i f_X(i)\\\\\n  var(X) = \\sigma^2_X &= \\sum_{i=0}^3 (i-\\mu_X)^2 f_X(i)\n\\end{align*}\n\n\n**Solution:**   \n\n*Binomial Distribution:*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\np = 0.7\nn = 3\npmf = dbinom(x,size = n, prob = p)\n(mu = sum(x*pmf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n(var = sum((x-mu)^2*pmf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.63\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n*Beta-Binomial Distribution*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx = 0:3\na = 7\nb = 3\nn = 3\npmf = dbbinom(x, size=n, alpha = a, beta = b)\n(mu = sum(x*pmf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.1\n```\n\n\n:::\n\n```{.r .cell-code}\n(var = sum((x-mu)^2*pmf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7445455\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nNotice that the two distributions have the same expected value, but the Beta-Binomial distribution has a greater variance.\n\n# Altham's Multiplicative Binomial Distribution\nWhile the Beta-Binomial enables us to model cases where winning has a clustering effect (e.g., a \"hot hand\").\n\n## Probability Mass Function\nThe mass function for this distribution is below. While it used to be available in the `MBD` package for `R`, this package is no longer available.\n$$f_X(x) = \\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}I(x \\in \\{0, 1, ..., n\\})$$\nwhere\n$$c = \\sum_{i=0}^n {n \\choose i} p^i (1-p)^{n-i} \\theta^{i(n-i)}$$ \n\n**Write a function in `R` called `daltbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match**\n\n**Solution:**  \n\n*Creating the Function*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbinom = function(n, x, p, theta){\n if(x < 0 || x > n || p < 0 || p > 1 || theta <= 0 || n < 0){\n    pmf = 0\n  }else{\n  i = 0:n\n  c = sum(choose(n,i) * p^i * (1-p)^(n-i) * theta^(i * (n-i)))\n  \n  pmf = (1/c) * choose(n,x) * p^x * (1-p)^(n-x) * theta^(x*(n-x))\n  }\n}\n```\n:::\n\n\n \\normalsize\n\n  \n*Plotting*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(df = tibble(\n  x = rep(0:3, 3),\n  pmf = c(\n    sapply(0:3, function(xi) daltbinom(3, xi, 0.7, 0.5)),\n    sapply(0:3, function(xi) daltbinom(3, xi, 0.7, 1)),\n    sapply(0:3, function(xi) daltbinom(3, xi, 0.7, 1.5))\n  ),\n  theta = c(\n    rep(\"0.5\", 4),\n    rep(\"1\", 4),\n    rep(\"1.5\", 4)\n  )\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 3\n       x    pmf theta\n   <int>  <dbl> <chr>\n 1     0 0.0512 0.5  \n 2     1 0.0896 0.5  \n 3     2 0.209  0.5  \n 4     3 0.650  0.5  \n 5     0 0.027  1    \n 6     1 0.189  1    \n 7     2 0.441  1    \n 8     3 0.343  1    \n 9     0 0.0151 1.5  \n10     1 0.238  1.5  \n11     2 0.555  1.5  \n12     3 0.192  1.5  \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  ggplot(aes(x = x, \n             y = pmf, \n             color = theta)) +\n    geom_point() +\n    theme_bw() +\n    labs(\n      x = \"Number of Legs Won (for A)\",\n      y = \"Probability\",\n      color = \"Theta\"\n    )\n```\n\n::: {.cell-output-display}\n![PMF of Altham’s multiplicative binomial for different values of θ.](Lab8WriteUp_files/figure-pdf/fig-altham-pmf-1.pdf){#fig-altham-pmf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n*Interpretation:* The most-likely outcome for the player with $\\theta = 0.5$ is 3 (plot is increasing, so they are more likely to win more legs than fewer legs). Furthermore, the player with $\\theta = 0.5$ has the highest chance of winning all 3 legs (a dominant outcome) compared to the other 2 players. The players with $\\theta = 1$ and $\\theta = 1.5$ don't see this strictly increasing pattern, and both are most likely to win 2 legs. What the three players *do* have in common is that the least likely outcome for all 3 is winning 0 games. When theta increases, it seems to make more balanced outcomes more probable, so 2-1 and 1-2 results become more likely.\n\n## Cumulative Distribution Function\n**Use your `daltbinom()` function to create a `paltbinom()` function for computing the CDF of this distribution. Use your function to plot the distribution where $p=0.70$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$.**\n\n**Solution:**\n*Function:*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npaltbinom = function(n, x, p, theta){\n  cdf = 0\n  for(i in 0:x){\n    cdf = cdf + daltbinom(n, i, p, theta)\n  }\n  return(cdf)\n}\n```\n:::\n\n\n \\normalsize\n\n*Plot:*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(df = tibble(\n  x = rep(0:3, 3),\n  cdf = c(\n    sapply(0:3, function(xi) paltbinom(3, xi, 0.7, 0.5)),\n    sapply(0:3, function(xi) paltbinom(3, xi, 0.7, 1)),\n    sapply(0:3, function(xi) paltbinom(3, xi, 0.7, 1.5))\n  ),\n  theta = c(\n    rep(\"0.5\", 4),\n    rep(\"1\", 4),\n    rep(\"1.5\", 4)\n  )\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 x 3\n       x    cdf theta\n   <int>  <dbl> <chr>\n 1     0 0.0512 0.5  \n 2     1 0.141  0.5  \n 3     2 0.350  0.5  \n 4     3 1      0.5  \n 5     0 0.027  1    \n 6     1 0.216  1    \n 7     2 0.657  1    \n 8     3 1      1    \n 9     0 0.0151 1.5  \n10     1 0.253  1.5  \n11     2 0.808  1.5  \n12     3 1      1.5  \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |>\n  ggplot(aes(x = x, \n             y = cdf, \n             color = theta)) +\n    geom_point(position = position_dodge(width = 0.2), size = 2) +\n    theme_bw() +\n    labs(\n      x = \"Number of Legs Won (for A)\",\n      y = \"Cumulative Probability\",\n      color = \"Theta\"\n    )\n```\n\n::: {.cell-output-display}\n![CDF of Altham’s multiplicative binomial for different values of θ.](Lab8WriteUp_files/figure-pdf/fig-altham-cdf-1.pdf){#fig-altham-cdf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## The Winning Probability\n**Compute the probability that Player A wins the match using Altham's Multiplicative Binomial Distribution. Compare your result to the Binomial and Negative Binomial results. Compare your results to the Beta-Binomial model, too. Make sure write out your probability statement and work to write it in terms of the distribution function (PMF/CDF) to plot the probability using `ggplot`.**\n\n**Solution:**\nSimilarly, we find the probability of winning 2 or more matches using the CDF: \n\n$$P(\\text{A wins}) = P(X \\ge 2) =  1 - P(X \\le 1) = 1 - F(1)$$\n\nThe difference this time is that our CDF has the additional parameter, $\\theta$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - sapply(c(0.5,1,1.5), function(t) paltbinom(3, 1, 0.7, t))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8592417 0.7840000 0.7469930\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n*Plot:*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf = tibble(\n  theta = seq(0.5, 1.5, by = 0.005),\n  win_prob = 1 - sapply(theta, function(t) paltbinom(3, 1, 0.7, t))\n)\n\ndf |>\n  ggplot(aes(x = theta, \n             y = win_prob)) +\n  geom_line() +\n  theme_bw() +\n  labs(\n    x = \"Theta\",\n    y = \"Probability A Wins (2 or more legs)\"\n  )\n```\n\n::: {.cell-output-display}\n![Probability that Player A wins as a function of θ.](Lab8WriteUp_files/figure-pdf/fig-altham-winprob-1.pdf){#fig-altham-winprob fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nAs $\\theta$ increases, the probability of winning decreases.\n\n# Altham's Multiplicative Beta-Binomial Distribution\nYou may have wondered -- \"Can we do the Beta thing with Altham's version of the Binomial Distribution?\" The answer is yes!\n\n## Probability Mass Function\nThe mass function for this distribution is below. \n$$f_X(x) = \\left[\\int_{0}^1 dp\n\\left(\\frac{1}{c} {n \\choose x} p^x (1-p)^{n-x} \\theta^{x(n-x)}\\right)\\left(\\frac{\\Gamma(\\alpha+\\beta)}{\\Gamma(\\alpha)\\Gamma(\\beta)} p^{\\alpha-1}(1-p)^{\\beta-1}\\right)\\right]I(x \\in \\{0, 1, ..., n\\})$$\n\n**Write a function in `R` called `daltbbinom()` for computing the PMF of this distribution. Use your function to plot the distribution where $\\alpha=7$ and $\\beta=3$ where $\\theta=0.50$, $\\theta=1$, and $\\theta=1.50$. Comment on the differences in the context of a best two-out-of-three match.**\\\n\n**Hint**: You can use the `integrate()` in `R` to compute the integral. Note that this requires the function to be vectorized -- it should be unless you have added any block conditionals.\n\n\n**Solution:**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaltbbinom = function(x, n, a, b, theta){\n\n  integrand = function(p){\n\n    i = 0:n\n    c = sum(choose(n,i) * p^i * (1-p)^(n-i) * theta^(i*(n-i)))\n\n    alt = (1/c) * choose(n,x) * p^x * (1-p)^(n-x) * theta^(x*(n-x))\n\n    beta = dbeta(p, a, b)\n\n    alt * beta\n  }\n  result = integrate(integrand, lower = 0, upper = 1)\n  result$value\n}\n```\n:::\n\n\n \\normalsize\n*Plot:*\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf = tibble(\n  x = rep(0:3, 3),\n\n  pmf = c(\n    sapply(0:3, function(xi) daltbbinom(xi, 3, 7, 3, 0.5)),\n    sapply(0:3, function(xi) daltbbinom(xi, 3, 7, 3, 1)),\n    sapply(0:3, function(xi) daltbbinom(xi, 3, 7, 3, 1.5))\n  ),\n\n  theta = c(\n    rep(\"0.5\", 4),\n    rep(\"1\", 4),\n    rep(\"1.5\", 4)\n  )\n)\n```\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(df |>\n  ggplot(aes(x = x, \n             y = pmf, \n             color = theta)) +\n  geom_point() +\n  theme_bw() +\n  labs(\n    x = \"Number of Legs Won (for A)\",\n    y = \"Probability\",\n    color = \"Theta\"\n  ))\n```\n\n::: {.cell-output-display}\n![PMF of Altham’s multiplicative Beta-Binomial distribution for different values of θ.](Lab8WriteUp_files/figure-pdf/fig-altham-betabinom-pmf-1.pdf){#fig-altham-betabinom-pmf fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nSimilar to the baseline Altham Binomial case, we notice that lower $\\theta$ (=0.5) makes winning all 3 legs the most likely outcome, whereas $\\theta = 1$ and $\\theta = 1.5$ have winning 2 games as the most likely outcome. \n\n\n\n\n# A Comparison\nCompute the probabilities for all outcomes for Player A.\n\n* Loses 0-2 (LL\"L\", LL\"W\")\n* Loses 1-2 (WLL, LWL)\n* Wins 2-0 (WW\"W\", WW\"L\")\n* Wins 2-1 (LWW, WLW)\n\n**Note**: You'll need to define these outcomes in terms of the random variable. \n\n**Create a bar plot (or column plot) using `ggplot` to show the probability of each outcome under the following conditions:**\n\n* **Binomial**\n* **Negative Binomial**\\\n**Note**: You can compute the lose probabilities the same way as the win probabilities using success probability ($1-p$)\n* **Beta-Binomial**\n* **Althman Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n* **Althman Beta-Binomial with $\\theta=0.50$ and $\\theta=1.5$**\n\n**Comment on the differences in the context of a best two-out-of-three match.**\n\n\n**Solution:**\n*Binomial Outcomes:*\n$$P(0-2) = f(0) + \\frac{1}{3}f(1)$$\n$$P(1-2) = \\frac{2}{3}f(1)$$\n\nThis is because there are 3 equally likely ways to have exactly one win: 1 of them gives a 0–2 result and 2 of them give a 1–2 result. Therefore, we split $f(1)$ using $\\frac{1}{3}$ and $\\frac{2}{3}$\n\n$$P(2-0) = f(3) + \\frac{1}{3}f(2)$$\n$$P(2-1) = \\frac{2}{3}f(2)$$\n\n*Negative Binomial Outcomes:*\n$$P(0-2) = (1 - p)^2 $$\n$$P(1-2) = 2p(1-p)^2 $$\n$$P(2-0) = P(X=0) = f(0) $$\n$$P(2-1) = P(X=1) = f(1)$$\n\n*Beta-Binomial Outcomes:*\nNote: these are the same as Binomial, except now $P$ is not fixed, but instead a random variable that follows the Beta distribution ($P \\sim \\text{Beta}(\\alpha, \\beta)$). \n$$P(0-2) = f(0) + \\frac{1}{3}f(1)$$\n$$P(1-2) = \\frac{2}{3}f(1)$$\n$$P(2-0) = f(3) + \\frac{1}{3}f(2)$$\n$$P(2-1) = \\frac{2}{3}f(2)$$\n\n*Altham Binomial Outcomes:*\nNote: these are the same as the Binomial, except the PMF is a different function with parameters $\\theta = 0.50$ and $\\theta = 1.5$ for the two separate cases.\n$$P(0-2) = f(0) + \\frac{1}{3}f(1)$$\n$$P(1-2) = \\frac{2}{3}f(1)$$\n$$P(2-0) = f(3) + \\frac{1}{3}f(2)$$\n$$P(2-1) = \\frac{2}{3}f(2)$$\n\n*Altham Beta-Binomial Outcomes:*\nNote: these are the same as the Altham Binomial (including the two values we use for $\\theta$), except now $P$ is not fixed, but instead a random variable that follows the Beta distribution ($P \\sim \\text{Beta}(\\alpha, \\beta)$). \n$$P(0-2) = f(0) + \\frac{1}{3}f(1)$$\n$$P(1-2) = \\frac{2}{3}f(1)$$\n$$P(2-0) = f(3) + \\frac{1}{3}f(2)$$\n$$P(2-1) = \\frac{2}{3}f(2)$$\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Probabilities\np=0.7\na=7\nb=3\n  #Binomial\n  binom1 = dbinom(x=0,size=3,prob=p) + (1/3)*dbinom(x=1,size=3,prob=p)\n  binom2 = (2/3)*dbinom(x=1,size=3,prob=p)\n  binom3 = dbinom(x=3,size=3,prob=p) + (1/3)*dbinom(x=2,size=3,prob=p)\n  binom4 = (2/3)*dbinom(x=2,size=3,prob=p)\n\n  #Negative Binomial\n  negBinom1 = (1-p)^2\n  negBinom2 = 2*p*(1-p)^2\n  negBinom3 = dnbinom(x=0,size=2,prob=p)\n  negBinom4 = dnbinom(x=1,size=2,prob=p)\n\n  #Beta Binomial\n  betaBinom1 = dbbinom(x=0,size=3,alpha=a,beta=b) + (1/3)*dbbinom(x=1,size=3,alpha=a,beta=b) \n  betaBinom2 = (2/3)*dbbinom(x=1,size=3,alpha=a,beta=b) \n  betaBinom3 = dbbinom(x=3,size=3,alpha=a,beta=b) + (1/3)*dbbinom(x=2,size=3,alpha=a,beta=b)\n  betaBinom4 = (2/3)*dbbinom(x=2,size=3,alpha=a,beta=b)\n\n  #Altham Binomial\n  altBinom1.05 = daltbinom(n=3,x=0,p=p,theta=0.5) + (1/3)*daltbinom(n=3,x=1,p=p,theta=0.5)\n  altBinom2.05 = (2/3)*daltbinom(n=3,x=1,p=p,theta=0.5)\n  altBinom3.05 = daltbinom(n=3,x=3,p=p,theta=0.5) + (1/3)*daltbinom(n=3,x=2,p=p,theta=0.5)\n  altBinom4.05 = (2/3)*daltbinom(n=3,x=2,p=p,theta=0.5)\n\n  altBinom1.15 = daltbinom(n=3,x=0,p=p,theta=1.5) + (1/3)*daltbinom(n=3,x=1,p=p,theta=1.5)\n  altBinom2.15 = (2/3)*daltbinom(n=3,x=1,p=p,theta=1.5)\n  altBinom3.15 = daltbinom(n=3,x=3,p=p,theta=1.5) + (1/3)*daltbinom(n=3,x=2,p=p,theta=1.5)\n  altBinom4.15 = (2/3)*daltbinom(n=3,x=2,p=p,theta=1.5)\n\n#Altham Beta Binomial\naltBBinom1.05 = daltbbinom(x=0,n=3,a=a,b=b,theta=0.5) + \n                (1/3)*daltbbinom(x=1,n=3,a=a,b=b,theta=0.5)\naltBBinom2.05 = (2/3)*daltbbinom(x=1,n=3,a=a,b=b,theta=0.5)\naltBBinom3.05 = daltbbinom(x=3,n=3,a=a,b=b,theta=0.5) \n                + (1/3)*daltbbinom(x=2,n=3,a=a,b=b,theta=0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03497286\n```\n\n\n:::\n\n```{.r .cell-code}\naltBBinom4.05 = (2/3)*daltbbinom(x=2,n=3,a=a,b=b,theta=0.5)\n\naltBBinom1.15 = daltbbinom(x=0,n=3,a=a,b=b,theta=1.5) + \n                (1/3)*daltbbinom(x=1,n=3,a=a,b=b,theta=1.5)\naltBBinom2.15 = (2/3)*daltbbinom(x=1,n=3,a=a,b=b,theta=1.5)\naltBBinom3.15 = daltbbinom(x=3,n=3,a=a,b=b,theta=1.5) + \n                (1/3)*daltbbinom(x=2,n=3,a=a,b=b,theta=1.5)\naltBBinom4.15 = (2/3)*daltbbinom(x=2,n=3,a=a,b=b,theta=1.5)\n\n\n# Plots\ndf.long = tibble(\n  outcome = rep(c(\"0-2\", \"1-2\", \"2-0\", \"2-1\"), 7),\n  prob = c(binom1, binom2, binom3, binom4,\n           negBinom1, negBinom2, negBinom3, negBinom4,\n           betaBinom1, betaBinom2, betaBinom3, betaBinom4,\n           altBinom1.05, altBinom2.05, altBinom3.05, altBinom4.05,\n           altBinom1.15, altBinom2.15, altBinom3.15, altBinom4.15,\n           altBBinom1.05, altBBinom2.05, altBBinom3.05, altBBinom4.05,\n           altBBinom1.15, altBBinom2.15, altBBinom3.15, altBBinom4.15),\n  model = rep(c(\"Binomial\",\n                \"Negative Binomial\",\n                \"Beta-Binomial\",\n                \"Altham Binomial (0.5)\",\n                \"Altham Binomial (1.5)\",\n                \"Altham Beta-Binomial (0.5)\",\n                \"Altham Beta-Binomial (1.5)\"),\n              each = 4)\n)\n\n# graphs\n#| label: fig-outcome-comparison\n#| fig-cap: \"Comparison of match outcome probabilities across models.\"\n#| fig-align: center\n\ndf.long |>\n  ggplot(aes(x = outcome, y = prob, fill = model)) +\n  geom_col(position = \"dodge\") +\n  theme_bw() +\n  labs(\n    x = \"Match Outcome\",\n    y = \"Probability\",\n    fill = \"Model\"\n  )\n```\n\n::: {.cell-output-display}\n![](Lab8WriteUp_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n**Commentary:**\nThe first and most trivial thing to point out is that the Binomial and Negative Binomial outcomes are identical. This is because the two use the same probabilities, but frames the situation differently. Whereas the simple binomial models is a fixed number of games, the negative binomial models a \"stopping criteria\", which leads to that same number of games being played with the same probabilities.\n\nThe Beta-Binomial model slightly changes these probabilities, but not in an incredibly noticeable way.\n\nThe Altham Binomial Model with $\\theta = 0.5$ shows an immense increase in the probability of 2-0 wins. The Altham Binomial Model with $\\theta = 1.5$ actually *decreases* the proportion of 2-0 wins from the normal Binomial case; however, it drastically improves the odds of 2-1 games.\n\nFollowing the prior Binomial-to-Beta-Binomial pattern, we see that the plots for Altham's Beta-Binomial match up very similarly with their non-Beta counterparts, just with slight variations due to the randomness of $P$.\n",
    "supporting": [
      "Lab8WriteUp_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}